### ISSUE TITLE
increase cache fetch duration check

### ISSUE THREAD

**Issue by kushalkolar** [nel-lab/mesmerize-core#100]
can you increase the difference that's checked here, the tests fail sometimes because the github CI pipeline computers aren't fast enough. Maybe something like 0.05? https://github.com/nel-lab/mesmerize-core/runs/7752247571?check_suite_focus=true#step:5:1652

**Comment by clewis7** [comment]
created PR for fix

**Comment by kushalkolar** [comment]
fixed in #102
