### ISSUE TITLE
cnmfe fails with keyerror: downsample_ratio

### ISSUE THREAD

**Issue by X4ndri** [nel-lab/mesmerize-core#162]
cnmfe is failing with traceback:
> 
> 'Traceback (most recent call last):
>   File "/home/aabdalq/miniconda3/envs/caiman/lib/python3.10/site-packages/mesmerize_core/algorithms/cnmfe.py", line 72, in run_algo
>     downsample_ratio = params["downsample_ratio"]
> KeyError: \'downsample_ratio\'
> '

cnmfe is run after motion correction was run. The `input_movie_path` parameter references a mcorr row in the dataframe like in the demos.

**Comment by kushalkolar** [comment]
A "downsample_ratio" key is required in the params dict, it determines how
much the movie is downsampled for making the correlation image.

Here's an example of the param dict for cnmfe:
https://github.com/nel-lab/mesmerize-core/blob/master/tests/params.py#L35

**Comment by kushalkolar** [comment]
cnmfe should run properly now with v02.1, should be out on conda-forge tomorrow
