### ISSUE TITLE
Add ability to remove items that have not been run

### ISSUE THREAD

**Issue by X4ndri** [nel-lab/mesmerize-core#169]
current tracebacks:

-```
--------------------------------------------------------------------------
BatchItemNotRunError                      Traceback (most recent call last)
Input In [11], in <cell line: 2>()
      2 for i, row in df.iterrows():
      3     if row.uuid not in keep:
----> 4         df.caiman.remove_item(row.uuid)

File ~/miniconda3/envs/caiman/lib/python3.10/site-packages/mesmerize_core/caiman_extensions/_utils.py:55, in _index_parser.<locals>._parser(instance, *args, **kwargs)
     52 else:
     53     args = (index, *args[1:])
---> 55 return func(instance, *args, **kwargs)

File ~/miniconda3/envs/caiman/lib/python3.10/site-packages/mesmerize_core/caiman_extensions/common.py:209, in CaimanDataFrameExtensions.remove_item(self, index, remove_data, safe_removal)
    207 if self._df.iloc[index]["algo"] == "mcorr":
    208     if safe_removal:
--> 209         children = self.get_children(index)
    210         if len(children) > 0:
    211             raise DependencyError(
    212                 f"This batch item's output is used as the input for batch items with the following UUIDs:\n"
    213                 f"{children}\n"
    214                 f"If you still want to force removal of this batch item use `safe_removal=False`"
    215             )

File ~/miniconda3/envs/caiman/lib/python3.10/site-packages/mesmerize_core/utils.py:48, in warning_experimental.<locals>.catcher.<locals>.fn(self, *args, **kwargs)
     38 @wraps(func)
     39 def fn(self, *args, **kwargs):
     40     warn(
     41         f"You are trying to use the following experimental feature, "
     42         f"this may change in the future without warning:\n"
   (...)
     46         stacklevel=2
     47     )
---> 48     return func(self, *args, **kwargs)

File ~/miniconda3/envs/caiman/lib/python3.10/site-packages/mesmerize_core/caiman_extensions/_utils.py:55, in _index_parser.<locals>._parser(instance, *args, **kwargs)
     52 else:
     53     args = (index, *args[1:])
---> 55 return func(instance, *args, **kwargs)

File ~/miniconda3/envs/caiman/lib/python3.10/site-packages/mesmerize_core/caiman_extensions/common.py:313, in CaimanDataFrameExtensions.get_children(self, index)
    307     raise TypeError(
    308         "`caiman.get_children()` extension maybe only be used with "
    309         "mcorr batch items, CNMF(E) items do not have children."
    310     )
    312 # get the output path for this mcorr item
--> 313 output_path = self._df.iloc[index].mcorr.get_output_path()
    315 # see if this output path shows up in the input_movie_path of any other batch item
    316 children = list()

File ~/miniconda3/envs/caiman/lib/python3.10/site-packages/mesmerize_core/caiman_extensions/_utils.py:14, in validate.<locals>.dec.<locals>.wrapper(self, *args, **kwargs)
     11 @wraps(func)
     12 def wrapper(self, *args, **kwargs):
     13     if self._series["outputs"] is None:
---> 14         raise BatchItemNotRunError("Item has not been run")
     16     if algo is not None:
     17         if algo not in self._series["algo"]:

BatchItemNotRunError: Item has not been run
```

**Comment by kushalkolar** [comment]
@X4ndri this should not be fixed after #202
