### ISSUE TITLE
Add ability to read .avi files

### ISSUE THREAD

**Issue by emelon8** [nel-lab/mesmerize-core#170]
I discussed adding the ability to read .avi files in mesmerize-core (for use both with running all algorithms and for visualization) with Kushal at the workshop. He suggested opening an issue. During the workshop, Kushal demonstrated how to do something similar to this with HDF5 files, and he suggested using Decord for the lazy loading, but I'm still not sure how to do it. Caiman itself can read them fine.

In addition, it would be nice if there was a way to point to multiple movie files at once. Not sure if that's possible to do too. The UCLA Miniscope software outputs .avi files (FFV1 encoding) with 1000 frames each by default, resulting in multiple movie files per recording, so I imagine incorporating both of these functionalities will be of interest to other users as well.

**Comment by emelon8** [comment]
Here are links to a few .avi files as examples (1000 frames per file, frame rate=30 Hz):
https://www.dropbox.com/s/mxubwry3ay28arw/0.avi?dl=0
https://www.dropbox.com/s/140o8c7egsjw68u/1.avi?dl=0
https://www.dropbox.com/s/k217hubnmmbgqbx/2.avi?dl=0

**Comment by kushalkolar** [comment]
Thanks for the example files, I see that these are `[x, y, colors]` arrays (the colors are such that it appears grayscale). Displaying `[x, y, CCC]` is kinda wonky using `frame_apply` functions in `ImageWidget` so I will just make it possible to use image arrays that are `[x, y, CCC]`: https://github.com/kushalkolar/fastplotlib/issues/129 

Will let you know when it's done.

**Comment by kushalkolar** [comment]
decord `VideoReader` is a bit messy so I wrapped it in a new `LazyVideo` class which also adds some useful features, will try to merge this week: #175 

you can load it like this and view as is (your vids seem to have the same vals across each RGB color so it appears grayscale), or convert it to just intensity values and view with a colormap

note that you will need `decord` installed: https://github.com/dmlc/decord

```python
from mesmerize_core.arrays import LazyVideo

path = "/home/kushal/Downloads/0.avi"
movie = LazyVideo(path)

# give to ImageWidget like any other array, cmap will be ignored and video will appear as is

# or you can convert to grayscale upon slicing
# rgb_weights can just be (1, 0, 0) since all your RGB values seem to be identical
movie = LazyVideo(path, as_grayscale=True, rgb_weights=(1, 0, 0))

# give movie to ImageWidget like any other array, can use any cmap
```

To use with `mesmerize_core` just return the LazyVideo instance in a function that you pass to `get_input_movie()`

```python
from mesmerize_core.arrays import LazyVideo

def video_reader(path):
    a = LazyVideo(path)  # you can use the other args if you want
    return a

input_movie = df.iloc[index].caiman.get_input_movie(video_reader)
```

**Comment by kushalkolar** [comment]
this will be out in v0.2.0 which was just released: https://github.com/nel-lab/mesmerize-core/releases/tag/v0.2.0

it will take a few hours for conda-forge to pick it up, closing this now but feel free to open another issue if there are issues with it.

**Comment by wmsheer** [comment]
Hi all,

I also would like to use the UCLA miniscope-formatted .avi output videos in mesmerize. I'm a bit lost in figuring out how to provide the .avi file to a `caiman.run()` function once it's loaded with the code block written above. E.g., if I define a function as you did above (`video_reader`) and then run it on the path containing my .avi, I get the following output: 
`def video_reader(path):
    a = LazyVideo(path) 
    return a

video_reader(movie_path)`

`LazyVideo @0x1ede991c100
None
Frames are computed only upon indexing
shape [frames, x, y]: (1000, 600, 600)`

Should I pass some component of that output to the batch df's input_movie_path column so that `caiman.run()` can make sense of it?

If I just pass the .avi path as I would a .tiff path and then try to run `process = row.caiman.run()`, I get the following output:

`Running a3a58dfe-9dcf-4c01-8988-5080065670eb with local backend
starting mc
mc failed, stored traceback in output`

Thanks!

**Comment by kushalkolar** [comment]
If you want to use an avi file as an input movie you just need to pass it to `df.caiman.add_item`: https://mesmerize-core.readthedocs.io/en/latest/api/common.html#mesmerize_core.CaimanDataFrameExtensions.add_item

`LazyVideo` is for visualization of the input video, you don't need to use it to run an item.

You can call `df.mcorr.get_output()` to print the traceback, likewise `df.cnmf.get_output()`

**Comment by wmsheer** [comment]
OK, that's what I first assumed. But if I pass the avi to `df.caiman.add_item`, I still cannot run the `caiman.run()` function successfully on a single batch item/row of my df (just with the mcorr algorithm for now). The error remains the same as above (`mc failed, stored traceback in output`), but `df.mcorr.get_output` returns the following error: `'DataFrame' object has no attribute 'mcorr'`.

If I go to my terminal, I see many similar error messages complaining about a GStreamer plug-in, e.g., `[ WARN:0@105.504] global C:\b\abs_74oeeuevib\croots\recipe\opencv-suite_1664548340488\work\modules\videoio\src\cap_gstreamer.cpp (2386) cv::handleMessage OpenCV | GStreamer warning: your GStreamer installation is missing a required plugin`.

Do you have any idea what may be happening?

**Comment by kushalkolar** [comment]
sorry it's `df.iloc[index].mcorr`, where `index` is the numerical index of the item.

**Comment by wmsheer** [comment]
No worries - was in the process of figuring that out when you replied.

Anyways, the traceback states the following: 

`Traceback (most recent call last):
  File "C:\Users\sheer\anaconda3\envs\mescore\lib\site-packages\mesmerize_core\algorithms\mcorr.py", line 67, in run_algo
    mc.motion_correct(save_movie=True)
  File "C:\Users\sheer\anaconda3\envs\mescore\lib\site-packages\caiman\motion_correction.py", line 252, in motion_correct
    self.motion_correct_pwrigid(template=template, save_movie=save_movie)
  File "C:\Users\sheer\anaconda3\envs\mescore\lib\site-packages\caiman\motion_correction.py", line 351, in motion_correct_pwrigid
    self.motion_correct_rigid()
  File "C:\Users\sheer\anaconda3\envs\mescore\lib\site-packages\caiman\motion_correction.py", line 296, in motion_correct_rigid
    _fname_tot_rig, _total_template_rig, _templates_rig, _shifts_rig = motion_correct_batch_rigid(
  File "C:\Users\sheer\anaconda3\envs\mescore\lib\site-packages\caiman\motion_correction.py", line 2824, in motion_correct_batch_rigid
    m = cm.load(fname, var_name_hdf5=var_name_hdf5, subindices=corrected_slicer)
  File "C:\Users\sheer\anaconda3\envs\mescore\lib\site-packages\caiman\base\movies.py", line 1567, in load
    start_frame = subindices[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0`

**Comment by kushalkolar** [comment]
what does your `df.add_item()` call look like?

**Comment by wmsheer** [comment]
^I also got the same error and traceback message when I tried using one of Eric's example .avi files above

**Comment by kushalkolar** [comment]
parent raw data path is supposed to be the top level path of your experiment directory structure

What if you set `parent_raw_data_path` as `C:/miniscope_files`

**Comment by wmsheer** [comment]
No change

**Comment by kushalkolar** [comment]
What does this give you:

```python
import caiman

caiman.load(["path"])
```

btw next time start a new issue so we don't spam the original person with notifications :)

**Comment by wmsheer** [comment]
Definitely will do, thanks (sorry, Eric!). Still a bit of a GitHub novice...

That returned an error: 

```Exception                                 Traceback (most recent call last)
Cell In[24], line 2
      1 import caiman
----> 2 caiman.load(['path'])

File ~\anaconda3\envs\mescore\lib\site-packages\caiman\base\movies.py:1442, in load(file_name, fr, start_time, meta_data, subindices, shape, var_name_hdf5, in_memory, is_behavior, bottom, top, left, right, channel, outtype, is3D)
   1439     if shape is not None:
   1440         logging.error('shape parameter not supported for multiple movie input')
-> 1442     return load_movie_chain(file_name,
   1443                             fr=fr,
   1444                             start_time=start_time,
   1445                             meta_data=meta_data,
   1446                             subindices=subindices,
   1447                             bottom=bottom,
   1448                             top=top,
   1449                             left=left,
   1450                             right=right,
   1451                             channel=channel,
   1452                             outtype=outtype,
   1453                             var_name_hdf5=var_name_hdf5,
   1454                             is3D=is3D)
   1456 elif isinstance(file_name, tuple):
   1457     print(f'**** Processing input file {file_name} as individualframes *****')

File ~\anaconda3\envs\mescore\lib\site-packages\caiman\base\movies.py:1773, in load_movie_chain(file_list, fr, start_time, meta_data, subindices, var_name_hdf5, bottom, top, left, right, z_top, z_bottom, is3D, channel, outtype)
   1771 mov = []
   1772 for f in tqdm(file_list):
-> 1773     m = load(f,
   1774              fr=fr,
   1775              start_time=start_time,
   1776              meta_data=meta_data,
   1777              subindices=subindices,
   1778              in_memory=True,
   1779              outtype=outtype,
   1780              var_name_hdf5=var_name_hdf5)
   1781     if channel is not None:
   1782         logging.debug(m.shape)

File ~\anaconda3\envs\mescore\lib\site-packages\caiman\base\movies.py:1728, in load(file_name, fr, start_time, meta_data, subindices, shape, var_name_hdf5, in_memory, is_behavior, bottom, top, left, right, channel, outtype, is3D)
   1726 else:
   1727     logging.error(f"File request:[{file_name}] not found!")
-> 1728     raise Exception(f'File {file_name} not found!')
   1730 return movie(input_arr.astype(outtype),
   1731              fr=fr,
   1732              start_time=start_time,
   1733              file_name=os.path.split(file_name)[-1],
   1734              meta_data=meta_data)

Exception: File path not found!
```

**Comment by kushalkolar** [comment]
Put the path in there, nor "path"

**Comment by wmsheer** [comment]
Whoops...

putting the actual video path returned `ValueError: negative dimensions are not allowed`

**Comment by kushalkolar** [comment]
Can you also try load(path), without the [ ] for list.

Trying to isolate if this is a issue with your video not loading in caiman.

**Comment by wmsheer** [comment]
similar issue. FWIW it's always replicating with Eric's example video as well.

Thanks so much for your help, btw!

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[35], line 2
      1 import caiman
----> 2 caiman.load("C:/miniscope_files/analyzed/5656/2023_04_07/10_23_51/0.avi")

File ~\anaconda3\envs\mescore\lib\site-packages\caiman\base\movies.py:1572, in load(file_name, fr, start_time, meta_data, subindices, shape, var_name_hdf5, in_memory, is_behavior, bottom, top, left, right, channel, outtype, is3D)
   1570     start_frame = 0
   1571 if not cv_failed:
-> 1572     input_arr = np.zeros((dims[0], height, width), dtype=np.uint8)
   1573     counter = 0
   1574     cap.set(1, start_frame)

ValueError: negative dimensions are not allowed


```

**Comment by kushalkolar** [comment]
Ok this seems to be a caiman thing, I'd post your last post right here with the load  call to the caiman repo.

**Comment by kushalkolar** [comment]
I wonder if loading avi files is different from other formats for caiman.

**Comment by kushalkolar** [comment]
If you use the caiman cnmfe demo does it load there?

**Comment by wmsheer** [comment]
Nope, doesn't seem to be. Same `index 0 is out of bounds for axis 0 with size 0` error message when trying to perform motion correction. I've previously attempted to use both caiman outside of mesmerize as well as the python implementation of NoRMCorre and neither have successfully been able to load the .avis

**Comment by wmsheer** [comment]
also a `negative dimensions are not allowed` message if I simply try to load the .avi

**Comment by kushalkolar** [comment]
Ah so it might be the files themselves. If you post on the caiman repo with a link to the file they can take a look.

**Comment by wmsheer** [comment]
Yeah that's what my suspicion has been for a while. Writing the post now. Thanks again for all the help, much appreciated.

**Comment by kushalkolar** [comment]
@wmsheer followed up in https://github.com/flatironinstitute/CaImAn/issues/1095
