### ISSUE TITLE
1-p/cnmfe

### ISSUE THREAD

**Issue by katesal327** [nel-lab/mesmerize-core#172]
Hi guys, thanks again for a great workshop and meeting you in person!

I am home now and trying to use mesmerize-core for 1-p/cnmfe...I walked through the demo you wrote, eric, and I understand the params better and the notebook works for me.

I want to now adapt this to mesmerize-core and I am wondering if it would be possible to have a demo cnmfe notebook included with a demo dictionary edited for the proper params? I am trying to input relevant cnmfe params in the params_cnmf dict and change the algo = 'cnmfe' but it is not making any memmap files and the output in False. I was able to enter gigSig_filt for the motion correction and change pw_rigid to False.

If y'all could help, that would be great! Prob not the only one with this problem, I hope. I think the error below has to do with the params dictionary input to the cnmfe

here is the current traceback for a failed row in the df: 

Traceback (most recent call last):
  File "C:\Users\scott\mambaforge\envs\mesmerize-core\lib\site-packages\mesmerize_core\algorithms\cnmfe.py", line 72, in run_algo
    downsample_ratio = params["downsample_ratio"]
KeyError: 'downsample_ratio'

**Comment by kushalkolar** [comment]
`downsample_ratio` is not one of the `CNMFParams` so it has to be outside of the `"main"` key: https://github.com/nel-lab/mesmerize-core/blob/master/tests/params.py#L35

It is used to downsample for pnr calculation

**Comment by katesal327** [comment]
ah, gotcha, I didn't realize there was an entire separate thing for cnmfe...wasn't clear to me, thanks. I will try that

**Comment by katesal327** [comment]
more prob obvious questions, but would a cell in the notebook look like this:

**params_cnmfe =\
{
    'main': # indicates that these are the "main" params for the CNMF algo
        {
            'fr': 50, # framerate, very important!
            'p': 1,
            'nb': 2,
            'merge_thr': 0.85,
            'rf': 15,
            'stride': 6, # "stride" for cnmf, "strides" for mcorr
            'K': None,
            'gSig': [3, 3],
            'ssub': 1,
            'tsub': 1,
            'method_init': 'corr_pnr',
            'min_SNR': 2.0,
            'rval_thr': 0.7,
            'use_cnn': True,
            'min_cnn_thr': 0.8,
            'cnn_lowest': 0.1,
            'decay_time': 0.4,
         },
    'refit': False, # If `True`, run a second iteration of CNMF
}
    "cnmfe_full": {
        "do_cnmfe": True,
        "keep_memmap": True,
        "main": {
            "gSig": (10, 10),
            "gSiz": (41, 41),
            "p": 1,
            "min_corr": 0.89,
            "min_pnr": 4,
            "rf": 50,
            "stride": 30,
            "gnb": 1,
            "nb_patch": 1,
            "K": 10,
            "ssub": 1,
            "tsub": 1,
            "ring_size_factor": 1.5,
            "merge_thresh": 0.7,
            "low_rank_background": False,
            "method_deconvolution": "oasis",
            "update_background_components": True,
            "del_duplicates": True,
        },
       "downsample_ratio": 1,
    },**

...or would I eliminate the top portion and just start at 

**params_cnmfe =\
{
"cnmfe_full": {
        "do_cnmfe": True,
        "keep_memmap": True,
        "main": {
            "gSig": (10, 10),
            "gSiz": (41, 41),
            "p": 1,
            "min_corr": 0.89,
            "min_pnr": 4,
            "rf": 50,
            "stride": 30,
            "gnb": 1,
            "nb_patch": 1,
            "K": 10,
            "ssub": 1,
            "tsub": 1,
            "ring_size_factor": 1.5,
            "merge_thresh": 0.7,
            "low_rank_background": False,
            "method_deconvolution": "oasis",
            "update_background_components": True,
            "del_duplicates": True,
        },
       "downsample_ratio": 1,
    }
}**

**Comment by kushalkolar** [comment]
It would look like the bottom, however CNMFE is often done in 2 steps, first just create the corr & pnr images to get the corr & pnr thresholds, and then do CNMFE. There currently isn't an example for this but I think you can just use the `fastplotlib` ImageWidget` and use the min max to help set `min_corr` and `min_pnr`

**Comment by katesal327** [comment]
got it, thanks

**Comment by katesal327** [comment]
OK still trying put crashing here:

---------------------------------------------------------------------------
BatchItemUnsuccessfulError                Traceback (most recent call last)
Cell In [43], line 1
----> 1 df.iloc[2].cnmf.get_output()

File ~\mambaforge\envs\mesmerize-core\lib\site-packages\mesmerize_core\caiman_extensions\_utils.py:24, in validate.<locals>.dec.<locals>.wrapper(self, *args, **kwargs)
     22 if not self._series["outputs"]["success"]:
     23     tb = self._series["outputs"]["traceback"]
---> 24     raise BatchItemUnsuccessfulError(f"Batch item was unsuccessful, traceback from subprocess:\n{tb}")
     25 return func(self, *args, **kwargs)

BatchItemUnsuccessfulError: Batch item was unsuccessful, traceback from subprocess:
Traceback (most recent call last):
  File "C:\Users\scott\mambaforge\envs\mesmerize-core\lib\site-packages\mesmerize_core\algorithms\cnmfe.py", line 59, in run_algo
    gSig = params["main"]["gSig"][0]
KeyError: 'gSig'

**Comment by katesal327** [comment]
is gSig supposed to be a single integer or like this [3,3]? CNMF params have it as [3,3]

**Comment by kushalkolar** [comment]
When giving the params dict to `caiman.add_item()`, `gSig` has to be `Tuple[int, int]`, and it must be included in the `"main"` key which is what you seem to be missing. What does `df.iloc[2].params` return for this dataframe (assuming you haven't removed the item at index 2).

**Comment by katesal327** [comment]
going through it again...able to get corr image and plot with imageW...get_pnr_image() failed...no pnr image path...which I can see. what step would that get generated? is that not included in the outputs after running mcorr.
**---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In [41], line 11
      8 mcorr_movie = df.iloc[index].mcorr.get_output()
     10 corr_image = df.iloc[index].caiman.get_corr_image()
---> 11 pnr_image = df.iloc[index].caiman.get_pnr_image()

File ~\mambaforge\envs\mesmerize-core\lib\site-packages\mesmerize_core\caiman_extensions\_utils.py:25, in validate.<locals>.dec.<locals>.wrapper(self, *args, **kwargs)
     23     tb = self._series["outputs"]["traceback"]
     24     raise BatchItemUnsuccessfulError(f"Batch item was unsuccessful, traceback from subprocess:\n{tb}")
---> 25 return func(self, *args, **kwargs)

File ~\mambaforge\envs\mesmerize-core\lib\site-packages\mesmerize_core\caiman_extensions\common.py:567, in CaimanSeriesExtensions.get_pnr_image(self)
    559 @validate()
    560 def get_pnr_image(self) -> np.ndarray:
    561     """
    562     Returns
    563     -------
    564     np.ndarray
    565         pnr image
    566     """
--> 567     path = self._series.paths.resolve(self._series["outputs"]["pnr-image-path"])
    568     return np.load(str(path))

KeyError: 'pnr-image-path'
**

**Comment by katesal327** [comment]
OK, setting up my params like this. I had to change "cnmfe_full" to "main", it didn't like it...so now there are two mains...doesn't make sense to me to have it that way. Still getting the following error on running the diffs...I think once the params dictionary is set-up correctly it will work?

# CNMFE params
params_cnmfe =\
{
    "main": 
    {       "do_cnmfe": True,
            "keep_memmap": True,
            
     "main":
     {
     
                "gSig": [3, 3],
                "gSiz": None,
                "p": 1,
                "min_corr": 0.8,
                "min_pnr": 10,
                "rf":40,
                "stride": 20,
                "gnb": 1,
                "nb_patch": 1,
                "K": None,
                "ssub": 1,
                "tsub": 1,
                "ring_size_factor": 1.5,
                "merge_thresh": 0.6,
                "low_rank_background": False,
                "method_deconvolution": "oasis",
                "update_background_components": True,
                "del_duplicates": True,
            },
     
            "downsample_ratio": 0.5,
    }
}

and getting this after running: df.caiman.get_params_diffs(algo="cnmfe", item_name=df.iloc[0]["item_name"])

C:\Users\scott\AppData\Local\Temp\ipykernel_15072\3903720550.py:1: FutureWarning: You are trying to use the following experimental feature, this may change in the future without warning:
CaimanDataFrameExtensions.get_params_diffs
This feature is new and the might improve in the future

  df.caiman.get_params_diffs(algo="cnmfe", item_name=df.iloc[0]["item_name"])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [19], line 1
----> 1 df.caiman.get_params_diffs(algo="cnmfe", item_name=df.iloc[0]["item_name"])

File ~\mambaforge\envs\mesmerize-core\lib\site-packages\mesmerize_core\utils.py:48, in warning_experimental.<locals>.catcher.<locals>.fn(self, *args, **kwargs)
     38 @wraps(func)
     39 def fn(self, *args, **kwargs):
     40     warn(
     41         f"You are trying to use the following experimental feature, "
     42         f"this may change in the future without warning:\n"
   (...)
     46         stacklevel=2
     47     )
---> 48     return func(self, *args, **kwargs)

File ~\mambaforge\envs\mesmerize-core\lib\site-packages\mesmerize_core\caiman_extensions\common.py:265, in CaimanDataFrameExtensions.get_params_diffs(self, algo, item_name)
    262 if sub_df.index.size == 0:
    263     raise NameError(f"The given `item_name`: {item_name}, does not exist in the DataFrame")
--> 265 all_variants = set(
    266     tuple(
    267         chain.from_iterable(
    268             [
    269                 tuple(p["main"].items()) for p in sub_df.params.values
    270             ]
    271         )
    272     )
    273 )
    275 counts = Counter([av[0] for av in all_variants])
    276 variants_exist = [param[0] for param in counts.items() if param[1] > 1]

TypeError: unhashable type: 'dict'

**Comment by katesal327** [comment]
> When giving the params dict to `caiman.add_item()`, `gSig` has to be `[int, int]`, and it must be included in the `"main"` key which is what you seem to be missing. What does `df.iloc[2].params` return for this dataframe (assuming you haven't removed the item at index 2).

df.iloc[1].params
{'main': {'do_cnmfe': True,
  'keep_memmap': True,
  'main': {'gSig': [3, 3],
   'gSiz': None,
   'p': 1,
   'min_corr': 0.8,
   'min_pnr': 10,
   'rf': 40,
   'stride': 20,
   'gnb': 1,
   'nb_patch': 1,
   'K': None,
   'ssub': 1,
   'tsub': 1,
   'ring_size_factor': 1.5,
   'merge_thresh': 0.6,
   'low_rank_background': False,
   'method_deconvolution': 'oasis',
   'update_background_components': True,
   'del_duplicates': True},
  'downsample_ratio': 0.5}}

**Comment by kushalkolar** [comment]
cnmfe should run properly now with v02.1, should be out on conda-forge tomorrow
