### ISSUE TITLE
CONDA_PREFIX_1 error when running , row.caiman.run()  on  jupyter lab mac m1

### ISSUE THREAD

**Issue by Vignesh-786** [nel-lab/mesmerize-core#174]
I'm getting this error when trying to run row.caiman.run() in the [mcorr_cnmf.ipynb](https://github.com/nel-lab/mesmerize-core/blob/master/notebooks/mcorr_cnmf.ipynb) demo.

complete traceback below:

<img width="488" alt="Screenshot 2023-02-07 at 12 25 56" src="https://user-images.githubusercontent.com/119962761/217232397-16dfede8-55c2-4edc-9a32-a887d85ff89d.png">

Thanks in advance

**Comment by kushalkolar** [comment]
What exact type of env, conda, miniconda, miniforge?

**Comment by vncntprvst** [comment]
Worth mentioning the temporary fix that Cameron Smith posted for that error during the workshop.
Add these lines before `row.caiman.run()`: 
```
# small fix for CONDA_PREFIX_1 not being found in environment
import os
str_to_remove = os.path.join(' ', 'envs', 'mescore')[1:]
conda_prefix_1_str = os.environ['CONDA_PREFIX'].replace(str_to_remove, '')
os.environ['CONDA_PREFIX_1'] = conda_prefix_1_str
```

**Comment by Vignesh-786** [comment]
it did work well . Thank you so much gusys

**Comment by kushalkolar** [comment]
> Worth mentioning the temporary fix that Cameron Smith posted for that error during the workshop. Add these lines before `row.caiman.run()`:
> 
> ```
> # small fix for CONDA_PREFIX_1 not being found in environment
> import os
> str_to_remove = os.path.join(' ', 'envs', 'mescore')[1:]
> conda_prefix_1_str = os.environ['CONDA_PREFIX'].replace(str_to_remove, '')
> os.environ['CONDA_PREFIX_1'] = conda_prefix_1_str
> ```

This is going to remain as the "fix" for now, it's in the demo notebooks too.
