### ISSUE TITLE
movie dimension changed from 3d to 4d when loading using lazytiff

### ISSUE THREAD

**Issue by asharma11** [nel-lab/mesmerize-core#178]
Hello!

Thank you again for a wonderful workshop!

I had an issue when loading my movie using lazytiff--the movie changed dimensions and was loaded as 4d array instead of 3. The original movie is 3d, and gets loaded correctly using caiman.

An example file of the video is uploaded here: https://www.dropbox.com/home/mesmerize_core_example_files

What would be the best way to address this issue? Thank you in advance for your help!

<img width="1068" alt="Screen Shot 2023-02-27 at 8 59 17 PM" src="https://user-images.githubusercontent.com/13437417/221733583-cf6f9dd8-0777-45a5-8330-38dd59b4fabb.png">

**Comment by kushalkolar** [comment]
@asharma11 you can manually set the shape after #192, will try to make a release this week.

**Comment by asharma11** [comment]
@kushalkolar Thank you very much!

**Comment by kushalkolar** [comment]
closing, feel free to open if it's still an issue
