### ISSUE TITLE
zmq issue AssertionError

### ISSUE THREAD

**Issue by dprotter** [nel-lab/mesmerize-core#179]
System: Ubuntu 20.04, 128 GB RAM x86
Fresh conda install of mesmirize-core

anaconda3/envs/mescore/lib/python3.10/site-packages/tornado/iostream.py", line 182, in advance
    assert 0 < size <= self._size
AssertionError

This error caused the video gui to become unresponsive. 

This seems to be an issue [others are having](https://discourse.jupyter.org/t/jupyter-notebook-zmq-message-arrived-on-closed-channel-error/17869) recently with jupyter. I was able to get mesmirize running well by downgrading jupyter-client==7.3.2 and tornado==6.1 
Not sure if this is a good long-term solution, but if anyone runs into this error it does work in the short term.

**Comment by kushalkolar** [comment]
We recommend jupyter lab and not jupyter notebook, do you get the same
issues with jupyter lab?

**Comment by dprotter** [comment]
i havent tried. Doesnt jupyter-lab use the same jupyter-client? Ill have to clone the environment and upgrade tornado and jupyter-client and test.

**Comment by kushalkolar** [comment]
Not sure, but I think jupyter lab is being maintained better so it's worth
trying.
