### ISSUE TITLE
Using list of paths for input_movie_paths

### ISSUE THREAD

**Issue by oterocoronel** [nel-lab/mesmerize-core#196]
I have a long recording split into several short files. I've tried to feed a list of paths (list_movie_paths) to mesmerize:

```
df.caiman.add_item(
    algo='mcorr',
    input_movie_path=list_movie_paths,
    params=mcorr_params1,
    item_name=list_movie_paths[0].stem, 
)
```

But I'm getting this error:
```
File ~/.mambaforge/envs/mescore/lib/python3.10/pathlib.py:578, in PurePath._parse_args(cls, args)
    576     parts += a._parts
    577 else:
--> 578     a = os.fspath(a)
    579     if isinstance(a, str):
    580         # Force-cast str subclasses to str (issue #21127)
    581         parts.append(str(a))

TypeError: expected str, bytes or os.PathLike object, not list
```

So it seems like Mesmerize only accepts one file at a time. I believe CaImAn already is compatible with lists of filenames, so I'm wondering if it would be possible to do the same in Mesmerize

**Comment by kushalkolar** [comment]
The only thing that's really a barrier to allowing this now is that the pandas extensions such as `caiman.get_input()` are used to lazy load the input files for visualization etc. We need to create a lazy array type that concatenates along the time dimension, more in #190

**Comment by kushalkolar** [comment]
This is something for another library to tackle, maybe pynapple
