### ISSUE TITLE
Caiman Notebook Demo Error

### ISSUE THREAD

**Issue by ambtetl** [nel-lab/mesmerize-core#198]
When going through the mcorr_cnmf.ipynb demo notebook I am receiving the following area when running the line of code to create a new batch. See below

```
Create a new batch
This creates a new pandas DataFrame with the columns that are necessary for mesmerize. In mesmerize we call this the batch DataFrame. You can add additional columns relevant to your experiment, but do not modify columns used by mesmerize.

Note that when you create a DataFrame you will need to use load_batch() to load it later. You cannot use create_batch() to overwrite an existing batch DataFrame

# create a new batch
df = create_batch(batch_path)
# to load existing batches use `load_batch()`
# df = load_batch(batch_path)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[12], line 2
      1 # create a new batch
----> 2 df = create_batch(batch_path)
      3 # to load existing batches use `load_batch()`
      4 # df = load_batch(batch_path)

NameError: name 'batch_path' is not defined
```

**Comment by kushalkolar** [comment]
looks like you didn't set any batch path, what does the rest of your notebook look like?

**Comment by ambtetl** [comment]
I am still following along with the youtube video for the installation. I have only been changing anything as noted in the video. My apologies as I know this is probably a silly error. 

What location should this batch_path be set to?

Python 3 (ipykernel)
from mesmerize_core import *
import numpy as np
from copy import deepcopy
import pandas as pd
You will need fastplotlib installed for the visualizations

from fastplotlib import ImageWidget
from ipywidgets import VBox, IntSlider, Layout
pd.options.display.max_colwidth = 120
Paths
These are the only variables you will need to modify in this demo notebook. You will need to set the paths according to your own caiman_data dir path

Explanation:

set_parent_raw_data_path() - This function from mesmerize_core sets the top level raw data directory. It is generally the top level directory for your raw experimental data. This allows you to move your experiment directory structure between computers, as long as you keep everything under the parent path the same.

For example,

On Linux based systems if you have your experimental data in the following dir:

/data/my_name/exp_top_level/....

You could set /data/my_name as the "parent raw data path", and you can then move exp_top_level/... between computers.

On windows:

D:/my_name/exp_top_level/...

You could set D:/my_name as the parent raw data path, and you can then move exp_top_level/... between computers.

Even on windows just use /, you do not have to worry about the annoying issue of \\ and \ on windows if you use pathlib :D

/
# for this demo set this dir as the path to your `caiman_data` dir
set_parent_raw_data_path("/Users/2Photon/caiman_data/")
PosixPath('/Users/2Photon/caiman_data')
Batch path, this is where caiman outputs will be organized
This can be anywhere, it does not need to be under the parent raw data path.

We recommend using pathlib instead of manually managing paths as strings. pathlib is just a part of the Python standard library, it makes it much easier to deal with paths and saves a lot of time in the long-run! It also makes your paths compatible across operating systems.

batch_path = get_parent_raw_data_path().joinpath("mesmerize-batch/batch.pickle")
Create a new batch
This creates a new pandas DataFrame with the columns that are necessary for mesmerize. In mesmerize we call this the batch DataFrame. You can add additional columns relevant to your experiment, but do not modify columns used by mesmerize.

Note that when you create a DataFrame you will need to use load_batch() to load it later. You cannot use create_batch() to overwrite an existing batch DataFrame







# create a new batch
df = create_batch(batch_path)
# to load existing batches use `load_batch()`
# df = load_batch(batch_path)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[12], line 2
      1 # create a new batch
----> 2 df = create_batch(batch_path)
      3 # to load existing batches use `load_batch()`
      4 # df = load_batch(batch_path)

NameError: name 'batch_path' is not defined

**Comment by kushalkolar** [comment]
did you run the cell that assigns `batch_path`?

**Comment by ambtetl** [comment]
Yes I ran the following cell: 

batch_path = get_parent_raw_data_path().joinpath("mesmerize-batch/batch.pickle")

**Comment by kushalkolar** [comment]
Can you restart the notebook and print the batch_path after setting it

**Comment by ambtetl** [comment]
That worked but I have ran into another error. I am watching the morning session from the September workshop. It is with the mcorr_cnmf notebook. When I go to run the single batch for the item line 0 I receive the following (including cells before). Within the the https://mesmerize-core.readthedocs.io/en/latest/user_guide.html#common-extensions I did not see any change for the caiman.run() command. I have tried using this without setting row = df.iloc[0] and running  process = df.iloc[0].caiman.run().
process.wait()

But the error is the same. 



Now we can see that there are many parameter variants, but it is not easy to see the differences in parameters between the rows that have the same item_name.
We can use the caiman.get_params_diffs() extension to see the unique parameters between rows with the same item_name
diffs = df.caiman.get_params_diffs(algo="mcorr", item_name=df.iloc[0]["item_name"])
diffs
/var/folders/vf/5vhc32q57wb046_rw3n58q780000gr/T/ipykernel_1447/1437176290.py:1: FutureWarning: You are trying to use the following experimental feature, this may change in the future without warning:
CaimanDataFrameExtensions.get_params_diffs
This feature is new and the might improve in the future

  diffs = df.caiman.get_params_diffs(algo="mcorr", item_name=df.iloc[0]["item_name"])
0    {'overlaps': (24, 24), 'max_shifts': (24, 24), 'strides': (48, 48)}
1    {'overlaps': (12, 12), 'max_shifts': (24, 24), 'strides': (24, 24)}
2      {'overlaps': (12, 12), 'max_shifts': (1, 1), 'strides': (24, 24)}
3      {'overlaps': (12, 12), 'max_shifts': (6, 6), 'strides': (24, 24)}
4    {'overlaps': (12, 12), 'max_shifts': (12, 12), 'strides': (24, 24)}
Name: params, dtype: object
Indexing rows and running batch item(s)
You can run a single batch item by calling caiman.run() on a Series (row) of the DataFrame. One way to get the row is integer indexing using df.iloc[index]
df.iloc[0]
# get the first batch item
row = df.iloc[0]
You can see how the various pandas.Series extensions are accessible at the level of dataframe rows.
Move the cursor to the end of the following line and press Tab on your keyboard. You can select the caiman.run() function and press Shift + Tab to see the docstring. You can also instead refer to the API docs. https://mesmerize-core.readthedocs.io/en/latest/api/common.html#mesmerize_core.CaimanSeriesExtensions

Note tab completion doesn't work if you use df.iloc[i].caiman.<method_name>, you need to apply the indexer to see the docstring.

row.caiman
<mesmerize_core.caiman_extensions.common.CaimanSeriesExtensions at 0x17c45d450>
Run a single batch item
Run the row that we have selected above, on Linux & Mac it will run in subprocess but on Windows it will run in the local kernel. If using the subprocess backend you can use run(wait=False) to not block the current kernel when running.

# run the first "batch item"
# this will run in a subprocess by default on Linux & Mac
# on windows it will run locally
process = row.caiman.run()
process.wait()
​
​
# reload dataframe from disk when done
df = df.caiman.reload_from_disk()
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[52], line 4
      1 # run the first "batch item"
      2 # this will run in a subprocess by default on Linux & Mac
      3 # on windows it will run locally
----> 4 process = row.caiman.run()
      5 process.wait()
      8 # reload dataframe from disk when done

File ~/miniconda3/envs/mescore/lib/python3.10/site-packages/mesmerize_core/caiman_extensions/cache.py:214, in Cache.invalidate.<locals>._invalidate.<locals>.__invalidate(instance, *args, **kwargs)
    208 if pre:
    209     self.cache.drop(
    210         self.cache.loc[self.cache["uuid"] == u].index,
    211         inplace=True
    212     )
--> 214 rval = func(instance, *args, **kwargs)
    216 if post:
    217     self.cache.drop(
    218         self.cache.loc[self.cache["uuid"] == u].index,
    219         inplace=True
    220     )

File ~/miniconda3/envs/mescore/lib/python3.10/site-packages/mesmerize_core/caiman_extensions/common.py:496, in CaimanSeriesExtensions.run(self, backend, wait, **kwargs)
    493     args_str += f" --data-path {get_parent_raw_data_path()}"
    495 # make the runfile
--> 496 runfile_path = make_runfile(
    497     module_path=os.path.abspath(
    498         ALGO_MODULES[self._series["algo"]].__file__
    499     ),  # caiman algorithm
    500     filename=runfile_path,  # path to create runfile
    501     args_str=args_str,
    502 )
    503 try:
    504     self.process = getattr(self, f"_run_{backend}")(
    505         runfile_path, wait=wait, **kwargs
    506     )

File ~/miniconda3/envs/mescore/lib/python3.10/site-packages/mesmerize_core/utils.py:110, in make_runfile(module_path, args_str, filename)
    104 f.write(f"#!/bin/bash\n")
    106 if "CONDA_PREFIX" in os.environ.keys():
    107     f.write(
    108         f'export CONDA_PREFIX={os.environ["CONDA_PREFIX"]}\n'
    109         f'export CONDA_PYTHON_EXE={os.environ["CONDA_PYTHON_EXE"]}\n'
--> 110         f'export CONDA_PREFIX_1={os.environ["CONDA_PREFIX_1"]}\n'
    111     )
    113 elif "VIRTUAL_ENV" in os.environ.keys():
    114     f.write(
    115         f'export PATH={os.environ["PATH"]}\n'
    116         f'export VIRTUAL_ENV={os.environ["VIRTUAL_ENV"]}\n'
    117         f'export LD_LIBRARY_PATH={os.environ["LD_LIBRARY_PATH"]}\n'
    118     )

File ~/miniconda3/envs/mescore/lib/python3.10/os.py:680, in _Environ.__getitem__(self, key)
    677     value = self._data[self.encodekey(key)]
    678 except KeyError:
    679     # raise KeyError with the original key value
--> 680     raise KeyError(key) from None
    681 return self.decodevalue(value)

KeyError: 'CONDA_PREFIX_1'

**Comment by kushalkolar** [comment]
Try this https://github.com/nel-lab/mesmerize-core/issues/174

What type of env is it, miniconda + installed with mamba?

**Comment by ambtetl** [comment]
The solution in #174 solved it! Thank you so much for all of your help thus far!  I am now running into another error in  the cnmf_viz demo notebook when I go to get the contours of the spatial components. I confirmed with the readthedocs that this should work.


Load outputs
CNMF pandas extensions API: https://mesmerize-core.readthedocs.io/en/latest/api/cnmf.html







# You can change this to plot the outputs for different batch items
index = 1

# get the motion corrected input movie as a memmap
cnmf_movie = df.iloc[index].caiman.get_input_movie()

# we can get the contours of the spatial components
contours, coms = df.iloc[index].cnmf.get_contours("all", swap_dim=False)

# and temporal components
temporal = df.iloc[index].cnmf.get_temporal("all")

ixs_good = df.iloc[index].cnmf.get_good_components()
ixs_bad = df.iloc[index].cnmf.get_bad_components()

cnmf_obj = df.iloc[indes].cnmf.get_output()
# You can change this to plot the outputs for different batch items
index = 1
​
# get the motion corrected input movie as a memmap
cnmf_movie = df.iloc[index].caiman.get_input_movie()
​
# we can get the contours of the spatial components
contours, coms = df.iloc[index].cnmf.get_contours("all", swap_dim=False)
​
# and temporal components
temporal = df.iloc[index].cnmf.get_temporal("all")
​
ixs_good = df.iloc[index].cnmf.get_good_components()
ixs_bad = df.iloc[index].cnmf.get_bad_components()
​
cnmf_obj = df.iloc[indes].cnmf.get_output()
---------------------------------------------------------------------------
WrongAlgorithmExtensionError              Traceback (most recent call last)
Cell In[21], line 8
      5 cnmf_movie = df.iloc[index].caiman.get_input_movie()
      7 # we can get the contours of the spatial components
----> 8 contours, coms = df.iloc[index].cnmf.get_contours("all", swap_dim=False)
     10 # and temporal components
     11 temporal = df.iloc[index].cnmf.get_temporal("all")

File ~/miniconda3/envs/mescore/lib/python3.10/site-packages/mesmerize_core/caiman_extensions/_utils.py:18, in validate.<locals>.dec.<locals>.wrapper(self, *args, **kwargs)
     16 if algo is not None:
     17     if algo not in self._series["algo"]:
---> 18         raise WrongAlgorithmExtensionError(
     19             f"<{algo} extension called for a <{self._series}> item"
     20         )
     22 if not self._series["outputs"]["success"]:
     23     tb = self._series["outputs"]["traceback"]

WrongAlgorithmExtensionError: <cnmf extension called for a <algo                                                                                                                                  mcorr
item_name                                                                                                                Sue_2x_3000_40_-46
input_movie_path                                                                                      example_movies/Sue_2x_3000_40_-46.tif
params              {'main': {'max_shifts': (24, 24), 'strides': (24, 24), 'overlaps': (12, 12), 'max_deviation_rigid': 3, 'border_nan':...
outputs             {'mean-projection-path': 9a24519e-0cd6-4343-bce6-7c0ddb9a2f8e/9a24519e-0cd6-4343-bce6-7c0ddb9a2f8e_mean_projection.n...
added_time                                                                                                              2023-04-28T12:08:36
ran_time                                                                                                                2023-04-28T12:09:22
algo_duration                                                                                                                     15.49 sec
comments                                                                                                                               None
uuid                                                                                                   9a24519e-0cd6-4343-bce6-7c0ddb9a2f8e
Name: 1, dtype: object> item

**Comment by kushalkolar** [comment]
see this in the traceback:

> WrongAlgorithmExtensionError: <cnmf extension called for a <algo mcorr

you've called a cnmf extension on an mcorr item

**Comment by ambtetl** [comment]
My apologies but what is the correct work around? I am just working through the youtube video of the September workshop. I have seen that things have since been updated and trying my best to bridge between the current the demo notebook and the video. Since the workbooks have been split, I am not certain on the proper bridge for this error

**Comment by kushalkolar** [comment]
You may be misunderstanding how DataFrames and mesmerize work. Each row in the DataFrame is a "batch item", and each item is either an mcorr or cnmf item. You cannot call a cnmf extension function on an mcorr item because that downs make sense, you can only call cnmf extensions on a cnmf item. So you need to index the appropriate item using df.iloc[ix], where "ix" is an integer index for the item you want, for example if an item at index 3 is a cnmf item then df.iloc[3].cnmf.some_cnmf_function() will work.

**Comment by ambtetl** [comment]
Since the code within the cell was in the demo notebook I wanted to confirm the proper coding. It definitely does make sense going back through. 

 I do have some additional questions regarding some of the differences from the demo notebook vs the video. Which I know there have been updates to the demo notebook since the video and just want to make sure I am working through everything correctly. So my apologies again if these are simple questions I really trying to learn python on the fly here. 


1) For the GUI layout for the component evaluation to have the sliders for SNF, CNN, etc, I tried the lines of code from the video and I have received the error below. 

##Component Evaluation ipywidgets for interactive component 
from ipywidgets import FloatSlider, FloatText, Label, HBox, VBox, link, Layout
from collections import OrderedDict
​


####THis is just GUI layout
​
​
#low threshold
lt = OrderedDict(
    rval_lowest = (-1.0, -1.0, 1.0),
    SNR_lowest = (0.5, 0., 100),
    cnn_lowest = (0.1, 0., 1.0),
)
​
#high tresholds 
ht = OrderedDict(
    rval_thr = (0.8, 0., 1.0),
    mim_SNR = (2.5, 0., 100),
    mim_cnn_thr = (0.9, 0., 1.0)
)
​
lw = list()
for k in lt:
    kwargs = dict(value=lt(k)(0), min=lt(k)(1), max=lt(k)(2), step = 0.01, description=k)
    slider = FloatSlider (**kwargs)
    entry = FloatText(**kwargs, layout=Layout(width="150px"))
    
    link((slider, "value"), (entry, "value"))
    lw.append(HBox([slider, entry]))
    
hw = list()
for k in ht:
    kwargs = dict(value=ht(k)(0), min=ht(k)(1), max=ht(k)(2), step=0.01, description=k)
    slider = FloatSlider(**kwargs)
    entry = FloatText(**kargs, layout=Layout(width="150px"))
    
    link((slider, "value"), (entry, "value"))
    
    hw.append(HBox([slider,entry]))
    
def get_eval_params():
    """get the values from the GUI"""
    
    _eval_params = [(w.children[0], description: w.children[0], value for w in ws) for ws in [lw,hw]]
    return (**_eval_params[0], **_eval_params[1])
  Cell In[238], line 38
    _eval_params = [(w.children[0], description: w.children[0], value for w in ws) for ws in [lw,hw]]
                                               ^
SyntaxError: invalid syntax

2) There are several cells for interactivity in the demo notebook but this was not in the video. Where is this to be ran? I have received errors for both of these
 FIRST INTERACTIVITY CELLS ERROR
Interactivity
# don't worry about understanding this function
def euclidean(source, target, event, new_data):
    """maps click events to contour"""
    # calculate coms of line collection
    indices = np.array(event.pick_info["index"])
    
    coms = list()
​
    for contour in target.graphics:
        coors = contour.data()[~np.isnan(contour.data()).any(axis=1)]
        com = coors.mean(axis=0)
        coms.append(com)
​
    # euclidean distance to find closest index of com 
    indices = np.append(indices, [0])
    
    ix = int(np.linalg.norm((coms - indices), axis=1).argsort()[0])
    
    target._set_feature(feature="colors", new_data=new_data, indices=ix)
    
    return None






# so we can view them one by one, first hide all of them
temporal_graphic[:].present = False
​
image_graphic = iw_cnmf.plot["image"]
​
# link image to contours
image_graphic.link(
    "click",
    target=contours_graphic,
    feature="colors", 
    new_data="w", 
    callback=euclidean
)
​
# link contour color changes (which are triggered by the click events as defined above) to everything else
​
# thickness of contour
contours_graphic.link("colors", target=contours_graphic, feature="thickness", new_data=5)
​
# toggle temporal component when contour changes color
contours_graphic.link("colors", target=temporal_graphic, feature="present", new_data=True)
# autoscale temporal plot to the current temporal component
temporal_graphic[:].present.add_event_handler(plot_temporal.auto_scale)
/Users/2Photon/miniconda3/envs/mescore/lib/python3.10/site-packages/fastplotlib/graphics/features/_base.py:148: UserWarning: Event handler <bound method PlotArea.auto_scale of unnamed: Plot @ 0x3c8121ab0
  parent: None
  Graphics:
	'temporal': LineCollection @ 0x3c8122d40
Collection of <155> Graphics
> has an unresolvable argspec, calling it without arguments
  warn(f"Event handler {func} has an unresolvable argspec, calling it without arguments")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/miniconda3/envs/mescore/lib/python3.10/site-packages/fastplotlib/graphics/features/_base.py:144, in GraphicFeature._call_event_handlers(self, event_data)
    143     else:
--> 144         func(event_data)
    145 else:

File ~/miniconda3/envs/mescore/lib/python3.10/site-packages/fastplotlib/layouts/_base.py:274, in PlotArea.auto_scale(self, maintain_aspect, zoom)
    273 if len(self.scene.children) > 0:
--> 274     width, height, depth = np.ptp(self.scene.get_world_bounding_box(), axis=0)
    275 else:

File <__array_function__ internals>:200, in ptp(*args, **kwargs)

File ~/miniconda3/envs/mescore/lib/python3.10/site-packages/numpy/core/fromnumeric.py:2695, in ptp(a, axis, out, keepdims)
   2694         return ptp(axis=axis, out=out, **kwargs)
-> 2695 return _methods._ptp(a, axis=axis, out=out, **kwargs)

File ~/miniconda3/envs/mescore/lib/python3.10/site-packages/numpy/core/_methods.py:282, in _ptp(a, axis, out, keepdims)
    281 def _ptp(a, axis=None, out=None, keepdims=False):
--> 282     return um.subtract(
    283         umr_maximum(a, axis, None, out, keepdims),
    284         umr_minimum(a, axis, None, None, keepdims),
    285         out
    286     )

TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
Cell In[226], line 2
      1 # so we can view them one by one, first hide all of them
----> 2 temporal_graphic[:].present = False
      4 image_graphic = iw_cnmf.plot["image"]
      6 # link image to contours

File ~/miniconda3/envs/mescore/lib/python3.10/site-packages/fastplotlib/graphics/_base.py:395, in CollectionIndexer.__setattr__(self, key, value)
    393     attr = getattr(self, key)
    394     if isinstance(attr, CollectionFeature):
--> 395         attr._set(value)
    396         return
    398 super().__setattr__(key, value)

File ~/miniconda3/envs/mescore/lib/python3.10/site-packages/fastplotlib/graphics/_base.py:446, in CollectionFeature._set(self, value)
    445 def _set(self, value):
--> 446     self[:] = value

File ~/miniconda3/envs/mescore/lib/python3.10/site-packages/fastplotlib/graphics/_base.py:459, in CollectionFeature.__setitem__(self, key, value)
    457 else:
    458     for fi in self._feature_instances:
--> 459         fi._set(value)

File ~/miniconda3/envs/mescore/lib/python3.10/site-packages/fastplotlib/graphics/features/_present.py:41, in PresentFeature._set(self, present)
     38         self._scene.remove(self._parent.world_object)
     40 self._data = present
---> 41 self._feature_changed(key=None, new_data=present)

File ~/miniconda3/envs/mescore/lib/python3.10/site-packages/fastplotlib/graphics/features/_present.py:55, in PresentFeature._feature_changed(self, key, new_data)
     46 pick_info = {
     47     "index": None,
     48     "collection-index": self._collection_index,
     49     "world_object": self._parent.world_object,
     50     "new_data": new_data
     51 }
     53 event_data = FeatureEvent(type="present", pick_info=pick_info)
---> 55 self._call_event_handlers(event_data)

File ~/miniconda3/envs/mescore/lib/python3.10/site-packages/fastplotlib/graphics/features/_base.py:149, in GraphicFeature._call_event_handlers(self, event_data)
    147 except:
    148     warn(f"Event handler {func} has an unresolvable argspec, calling it without arguments")
--> 149     func()

File ~/miniconda3/envs/mescore/lib/python3.10/site-packages/fastplotlib/layouts/_base.py:274, in PlotArea.auto_scale(self, maintain_aspect, zoom)
    271 self.camera.maintain_aspect = maintain_aspect
    273 if len(self.scene.children) > 0:
--> 274     width, height, depth = np.ptp(self.scene.get_world_bounding_box(), axis=0)
    275 else:
    276     width, height, depth = (1, 1, 1)

File <__array_function__ internals>:200, in ptp(*args, **kwargs)

File ~/miniconda3/envs/mescore/lib/python3.10/site-packages/numpy/core/fromnumeric.py:2695, in ptp(a, axis, out, keepdims)
   2693     else:
   2694         return ptp(axis=axis, out=out, **kwargs)
-> 2695 return _methods._ptp(a, axis=axis, out=out, **kwargs)

File ~/miniconda3/envs/mescore/lib/python3.10/site-packages/numpy/core/_methods.py:282, in _ptp(a, axis, out, keepdims)
    281 def _ptp(a, axis=None, out=None, keepdims=False):
--> 282     return um.subtract(
    283         umr_maximum(a, axis, None, out, keepdims),
    284         umr_minimum(a, axis, None, None, keepdims),
    285         out
    286     )

TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

SECOND INTERACTIVE CELLS ERROR
Interactivity just like before






# so we can view them one by one, first hide all of them
temporal_graphic[:].present = False
​
# link image to contours
movie_graphic.link(
    "click",
    target=contours_movie,
    feature="colors", 
    new_data="w", 
    callback=euclidean  # we cam re-use it from before
)
​
# link image to contours
rcm_graphic.link(
    "click",
    target=contours_rcm,
    feature="colors", 
    new_data="w", 
    callback=euclidean  # we cam re-use it from before
)
​
# contours colors -> contor thickness
contours_movie.link("colors", target=contours_movie, feature="thickness", new_data=5)
contours_rcm.link("colors", target=contours_rcm, feature="thickness", new_data=5)
​
# contours_movie <-> contours_rcm
contours_rcm.link("colors", target=contours_movie, feature="colors", new_data="w", bidirectional=True)
​
# temporal stack events
temporal_stack.link("click", target=temporal_stack, feature="colors", new_data="w")
temporal_stack.link("colors", target=temporal_stack, feature="thickness", new_data=4)
​
# contours <-> temporal stack
contours_movie.link("colors", target=temporal_stack, feature="colors", new_data="w", bidirectional=True)
​
# temporal stack -> temporal single
temporal_stack.link("colors", target=temporal_graphic, feature="present", new_data=True)
​
# autoscale temporal plot to the current temporal component
temporal_graphic[:].present.add_event_handler(plot_temporal_single.auto_scale)
/Users/2Photon/miniconda3/envs/mescore/lib/python3.10/site-packages/fastplotlib/graphics/features/_base.py:115: UserWarning: Event handler <bound method Interaction._event_handler of LineCollection @ 0x47244f370
Collection of <71> Graphics> is already registered.
  warn(f"Event handler {handler} is already registered.")
/Users/2Photon/miniconda3/envs/mescore/lib/python3.10/site-packages/fastplotlib/graphics/features/_base.py:115: UserWarning: Event handler <bound method Interaction._event_handler of LineCollection @ 0x47244f190
Collection of <71> Graphics> is already registered.
  warn(f"Event handler {handler} is already registered.")
/Users/2Photon/miniconda3/envs/mescore/lib/python3.10/site-packages/fastplotlib/graphics/features/_base.py:115: UserWarning: Event handler <bound method Interaction._event_handler of LineStack @ 0x47244f580
Collection of <71> Graphics> is already registered.
  warn(f"Event handler {handler} is already registered.")

3) Final question (hopefully). What is the proper call to get a data file as you could export previously from the legacy version that includes frequency of firing, duration, amplitude, total signal, and spike?

**Comment by kushalkolar** [comment]
The component evaluation nb isn't really ready yet. It will be at least a few weeks until it is ready.

Any downstream analysis will have to be done on your own and depends on your scientific questions, you can however continue using the batch dataframe if you want since it's just pandas.

**Comment by kushalkolar** [comment]
You can check the pull requests periodically to see what's been merged. I
usually send a message in the gitter as well.
