### ISSUE TITLE
add cnmf extension for component eval

### ISSUE THREAD

**Issue by kushalkolar** [nel-lab/mesmerize-core#20]
component evaluation should be done here within the backend, not in mesmerize-napari. write a cnmf extension that wraps `cnmf_obj.estimates.filter_components`.

Should it store this as a new batch item in the dataframe or update an existing item and just update the eval_kwargs of the params? @ArjunPutcha thoughts?

**Comment by ArjunPutcha** [comment]
I would think update eval kwargs within same item. Number of rows would get out of hand if we create a new batch item for each update of eval components (especially with update_live)

**Comment by ArjunPutcha** [comment]
Should we create a separate button to specifically save new eval kwargs, set it to save only when eval gui is closed/window is closed (so save most recent choice of eval kwargs), or continuously save as updates occur. I would think the first two options are better (preferably the first).

**Comment by kushalkolar** [comment]
> I would think update eval kwargs within same item. Number of rows would get out of hand if we create a new batch item for each update of eval components (especially with update_live)

Good idea. It should only be saved after the user saves whatever they're happy with. We can add a flag to the params dict that indicates if eval components has been run on it by the user?

**Comment by kushalkolar** [comment]
> Should we create a separate button to specifically save new eval kwargs, set it to save only when eval gui is closed/window is closed (so save most recent choice of eval kwargs), or continuously save as updates occur. I would think the first two options are better (preferably the first).

We should have an explicit save button
