### ISSUE TITLE
Cannot import name 'get_color' when importing fastplotlib

### ISSUE THREAD

**Issue by msoheib** [nel-lab/mesmerize-core#206]
I keep getting this error using the demo ntoebook.

I tried reinstalling fastplotlib but the error persists.

`ImportError                               Traceback (most recent call last)
Cell In[2], line 2
      1 from fastplotlib import ImageWidget, Plot, GridPlot
----> 2 from fastplotlib.utils import get_colors
      3 from fastplotlib.graphics.line_slider import LineSlider
      4 from ipywidgets import VBox, IntSlider, Layout
ImportError: cannot import name 'get_colors' from 'fastplotlib.utils'`

**Comment by kushalkolar** [comment]
Which notebook

**Comment by msoheib** [comment]
cnmf_eval.ipynb

**Comment by kushalkolar** [comment]
That nb isn't ready yet, I'll message on gitter when it is ready.
