### ISSUE TITLE
Cloud files

### ISSUE THREAD

**Issue by vkonan** [nel-lab/mesmerize-core#207]
Is there any way to feed paths to mesmerize for files that reside in the cloud without downloading them?

I'm exploring how boxsdk package works but I get this following error. I'm guessing there is more to it than just feeding the path coming from boxsdk.

**Comment by kushalkolar** [comment]
I don't see the error.

If you have a way to mount the remote filesystem that's probably the easiest way.

For running caiman algorithms, the path is just fed directly to caiman so if caiman supports it then it should work. Visualization of input movies on a remote server will probably be sluggish unless your have a fast connection.

**Comment by vkonan** [comment]
Sorry I forgot to include the error. However, I think it's because I still am not sure how to properly call files on box remotely.

Your point about sluggish connectivity is well taken. I don't think it would be a great idea to compound computation times with the problems that come with remote connectivity.

I'm going to close this issue because I don't think I want to pursue trying to connect remotely. Thanks for your input!
