### ISSUE TITLE
Issues with ImageWidget.plot

### ISSUE THREAD

**Issue by asharma11** [nel-lab/mesmerize-core#217]
Hi Kushal,

Did the function 'plot' for ImageWidget get switched to something else? I can't find it in the class when looking at the functions here: https://github.com/fastplotlib/fastplotlib/blob/master/fastplotlib/widgets/image.py. and it throws an error when I call the plot function _AttributeError: 'ImageWidget' object has no attribute 'plot'_

By switching to calling the gridplot function instead, I can get some of the stuff working e.g `iw.plot.canvas.close()`

But it doesn't work when I replace plot with gridplot for the corr-pnr seeding for CNMF-E. This is the error it throws: 

Thanks in advance for your time and help! 

KeyError                                  Traceback (most recent call last)
Cell In[38], line 77
     74 iw_corr_pnr.gridplot.canvas.set_logical_size(650, 300) # changed to gridplot
     75 iw_thres_movie.gridplot.canvas.set_logical_size(650, 600) # changed plot to gridplot
---> 77 VBox([iw_corr_pnr.show(), iw_thres_movie.show()])

File ~\mambaforge\envs\mescore\lib\site-packages\fastplotlib\widgets\image.py:923, in ImageWidget.show(self, toolbar)
    920     return VBox([self.gridplot.show(toolbar=False), self._vbox_sliders])
    922 if self.toolbar is None:
--> 923     self.toolbar = ImageWidgetToolbar(self)
    925 return VBox(
    926     [
    927         self.gridplot.show(toolbar=True),
   (...)
    930     ]
    931 )

File ~\mambaforge\envs\mescore\lib\site-packages\fastplotlib\widgets\image.py:950, in ImageWidgetToolbar.__init__(self, iw)
    945 self.plot = iw.gridplot
    947 self.reset_vminvmax_button = Button(value=False, disabled=False, icon='adjust',
    948                                     layout=Layout(width='auto'), tooltip='reset vmin/vmax')
--> 950 self.step_size_setter = BoundedIntText(value=1, min=1, max=self.iw.sliders['t'].max, step=1,
    951                                        description='Step Size:', disabled=False,
    952                                        description_tooltip='set slider step', layout=Layout(width='150px'))
    953 self.play_button = Play(
    954     value=0,
    955     min=iw.sliders["t"].min,
   (...)
    958     description="play/pause",
    959     disabled=False)
    961 self.widget = HBox([self.reset_vminvmax_button, self.play_button, self.step_size_setter])

KeyError: 't'

**Comment by kushalkolar** [comment]
we need to update the demo nbs w.r.t the latest fastplotlib, #213, #218

**Comment by JohnStout** [comment]
I'm also having issues with this while trying to use mesmerize to view components overlaid on video. 

No attribute "plot" for the ImageWidget object. Is there a quick fix for this, or could I use an older version of fastplotlib that worked with the demos on mesmerize?

**Comment by kushalkolar** [comment]
Thanks for posting an issue!

Yes to simplify things we recently changed ImageWidget so that it always
uses a Gridplot even if only a single Subplot is shown (uses shape (1, 1)).

So you can do "iw.grid_plot" to access it.

**Comment by JohnStout** [comment]
Thank you! I'll comment again when I try

**Comment by kushalkolar** [comment]
related: in the meantime you can checkout the notebooks in the `update_notebooks` branch: https://github.com/nel-lab/mesmerize-core/tree/update_notebooks/notebooks

**Comment by kushalkolar** [comment]
should be fixed by #218
