### ISSUE TITLE
Unable to install mesmerize_core

### ISSUE THREAD

**Issue by zhouyi0812** [nel-lab/mesmerize-core#219]
Hi,

I was unable to use mesmerize for reconstruct the movie by following the installation from the instruction of the installation with mamba. 

(caiman) yizhou@DN51s0e6 ~ % mamba activate mescore
Run 'mamba init' to be able to run mamba activate/deactivate
and start a new shell session. Or use conda to activate/deactivate.

----> 1 import mesmerize_core

ModuleNotFoundError: No module named 'mesmerize_core'

In [2]: mesmerize_core.__version__

**Comment by kushalkolar** [comment]
It looks like you're not in the right environment:

> Run 'mamba init' to be able to run mamba activate/deactivate
and start a new shell session. Or use conda to activate/deactivate.

**Comment by zhouyi0812** [comment]
I tried 'mamba init' and then restart my terminal. Then tried "mamba activate memerize_core", it return: (base) yizhou@DN51s0e6 ~ % mamba activate mesmerize_core
Traceback (most recent call last):
  File "/Users/yizhou/miniconda3/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/Users/yizhou/miniconda3/lib/python3.10/site-packages/mamba/mamba.py", line 49, in <module>
    import libmambapy as api
  File "/Users/yizhou/miniconda3/lib/python3.10/site-packages/libmambapy/__init__.py", line 7, in <module>
    raise e
  File "/Users/yizhou/miniconda3/lib/python3.10/site-packages/libmambapy/__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: dlopen(/Users/yizhou/miniconda3/lib/python3.10/site-packages/libmambapy/bindings.cpython-310-darwin.so, 2): Library not loaded: @rpath/libarchive.13.dylib
  Referenced from: /Users/yizhou/miniconda3/lib/libmamba.2.0.0.dylib
  Reason: image not found

I think I install mesmerize_core in caiman........

**Comment by kushalkolar** [comment]
Are you able to import it in your caiman environment if you installed it in that env?

How did you install caiman? Was it not using mamba?

**Comment by zhouyi0812** [comment]
what do you mean with import it in caiman? if I enter 'mamba' in caiman envior:

(caiman) yizhou@DN51s0e6 ~ % mamba
usage: mamba [-h] [-V] command ...

conda is a tool for managing and deploying applications, environments and packages.

Options:

positional arguments:
  command
    clean             Remove unused packages and caches.
    compare           Compare packages between conda environments.
    config            Modify configuration values in .condarc. This is modeled
                      after the git config command. Writes to the user
                      .condarc file (/Users/yizhou/.condarc) by default. Use
                      the --show-sources flag to display all identified
                      configuration locations on your computer.


I can't remember how I install caiman, and I use Mac, probably mamba is not required for it.

**Comment by kushalkolar** [comment]
I asked Pat, you have to activate with conda even if you used mamba to
install it.

Use:
conda activate env-name

(replace env-name with the name of the environment that has mesmerize-core)

**Comment by zhouyi0812** [comment]
Thank you!

I checked my conda environment and found I install mesmerize_core in caiman, and I: conda activate caiman; and check in ipython: pip install mesmerize_core; and mesmerize_core.__version, and it return: .

10/site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyterlab->mesmerize_core) (0.2.2)
Requirement already satisfied: pycparser in ./miniconda3/envs/caiman/lib/python3.10/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->jupyter-server<3,>=2.4.0->jupyterlab->mesmerize_core) (2.21)
Requirement already satisfied: arrow>=0.15.0 in ./miniconda3/envs/caiman/lib/python3.10/site-packages (from isoduration->jsonschema>=4.17.3->jupyterlab-server<3,>=2.19.0->jupyterlab->mesmerize_core) (1.2.3)

In [2]: mesmerize_core.__version__
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 mesmerize_core.__version__

NameError: name 'mesmerize_core' is not defined

                         /Users/yizhou/Library/r-miniconda
                         /Users/yizhou/Library/r-miniconda/envs/r-reticulate
base                  *  /Users/yizhou/miniconda3
caiman                   /Users/yizhou/miniconda3/envs/caiman
                         /Users/yizhou/miniconda3/envs/caiman/envs/mescore
caiman_env               /Users/yizhou/miniconda3/envs/caiman_env
opencv                   /Users/yizhou/miniconda3/envs/opencv
py39                     /Users/yizhou/miniconda3/envs/py39
snakes                   /Users/yizhou/miniconda3/envs/snakes
snowflakes               /Users/yizhou/miniconda3/envs/snowflakes
                         /Users/yizhou/opt/anaconda3

**Comment by kushalkolar** [comment]
Don't use pip to install mesmerize-core in a conda environment. If you've
installed mesmerize-core you can import it in ipython, jupyter etc.
