### ISSUE TITLE
Import hdf5 file with mes

### ISSUE THREAD

**Issue by zhouyi0812** [nel-lab/mesmerize-core#235]
Hello! 
Just want to check I use the code to import the file and want to print estimate obj, but encountered some error:

```python
filename = "023C2d24_B3_C7_1_00d00h00m-005.hdf5"
cnm.save(filename)
from caiman.source_extraction.cnmf.cnmf import load_CNMF
df = load_CNMF('023C2d24_B3_C7_1_00d00h00m-005.hdf5')
from mesmerize_core import load_batch
cnmf_obj = df.iloc[0].cnmf.get_output()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[35], line 1
----> 1 cnmf_obj = df.iloc[0].cnmf.get_output()

AttributeError: 'CNMF' object has no attribute 'iloc'
```

Thank you for your guidance!

**Comment by kushalkolar** [comment]
You're misunderstanding what `mesmerize-core` is, it's a framework for organizing multiple runs of mcorr or cnmf using pandas dataframes (tables). I would start from the beginning of the `mcorr_cnmf` demo notebook to understand it: https://github.com/nel-lab/mesmerize-core/blob/master/notebooks/mcorr_cnmf.ipynb 

The demo notebook uses `fastplotlib` for visualization, see this for installation instructions: https://github.com/fastplotlib/fastplotlib#notebook

Note: you will need `jupyterlab`, `jupyter notebook` is not supported. notebook v7 _might_ work but we haven't tested it.

**Comment by zhouyi0812** [comment]
Thank you very much!!!! I just realized this is such a powerful tool to save my time!

I go over the whole demo from the link at jupyter lab at the google cloud engine. And when I visualize there is an error:


[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'RemoteFrameBufferModel' from module 'jupyter_rfb'
Error: No version of module jupyter_rfb is registered
    at f.loadClass (https://31bec6dfc9e5114b-dot-us-central1.notebooks.googleusercontent.com/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.b4eddbb09f5fd50a4007.js?v=b4eddbb09f5fd50a4007:1:74934)

I tried to intall the jupyter_rfb but it just does not work.
Thank you!!!!!!

**Comment by kushalkolar** [comment]
Are you using jupyter lab and not colab? Fastplotlib is only supported in
jupyterlab at the moment.

You will have to restart the jupyterlab server after installed jupyter_rfb
in the environment. Generally anytime you install ipywidget or jupyter
related libraries you will have to restart jupyterlab because it has to
load them in.

**Comment by zhouyi0812** [comment]
I am using the jupyter lab, in google cloud engine. And here is the error

Missing downlevel flags: DownlevelFlags(SURFACE_VIEW_FORMATS)
The underlying API or device in use does not support enough features to be a fully compliant implementation of WebGPU. A subset of the features can still be used. If you are running this program on native and not in a browser and wish to limit the features you use to the supported subset, call Adapter::downlevel_properties or Device::downlevel_properties to get a listing of the features the current platform supports.
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.

[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'RemoteFrameBufferModel' from module 'jupyter_rfb'
Error: No version of module jupyter_rfb is registered
    at f.loadClass (https://31bec6dfc9e5114b-dot-us-central1.notebooks.googleusercontent.com/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.b4eddbb09f5fd50a4007.js?v=b4eddbb09f5fd50a4007:1:74934)
    at f.loadModelClass (https://31bec6dfc9e5114b-dot-us-central1.notebooks.googleusercontent.com/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.9f709c2076672b1bfe2b.js?v=9f709c2076672b1bfe2b:1:10729)
    at f._make_model (https://31bec6dfc9e5114b-dot-us-central1.notebooks.googleusercontent.com/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.9f709c2076672b1bfe2b.js?v=9f709c2076672b1bfe2b:1:7517)
    at f.new_model (https://31bec6dfc9e5114b-dot-us-central1.notebooks.googleusercontent.com/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.9f709c2076672b1bfe2b.js?v=9f709c2076672b1bfe2b:1:5137)
    at f.handle_comm_open (https://31bec6dfc9e5114b-dot-us-central1.notebooks.googleusercontent.com/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.9f709c2076672b1bfe2b.js?v=9f709c2076672b1bfe2b:1:3894)
    at _handleCommOpen (https://31bec6dfc9e5114b-dot-us-central1.notebooks.googleusercontent.com/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.b4eddbb09f5fd50a4007.js?v=b4eddbb09f5fd50a4007:1:73471)
    at KernelConnection._handleCommOpen (https://31bec6dfc9e5114b-dot-us-central1.notebooks.googleusercontent.com/static/lab/jlab_core.c95dd43b5c3cfebcc4a0.js?v=c95dd43b5c3cfebcc4a0:76174:19)
    at async KernelConnection._handleMessage (https://31bec6dfc9e5114b-dot-us-central1.notebooks.googleusercontent.com/static/lab/jlab_core.c95dd43b5c3cfebcc4a0.js?v=c95dd43b5c3cfebcc4a0:76342:25)

(base) jupyter@instance-20231019-090835:~$ conda activate mescore
(mescore) jupyter@instance-20231019-090835:~$ [Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'RemoteFrameBufferModel' from module 'jupyter_rfb'
Error: No version of module jupyter_rfb is registered
    at f.loadClass (https://31bec6dfc9e5114b-dot-us-ce
bash: [Open: command not found
bash: Failed: command not found
bash: Error:: command not found
bash: syntax error near unexpected token `('
(mescore) jupyter@instance-20231019-090835:~$ pip list | grep jupyter_rfb
(mescore) jupyter@instance-20231019-090835:~$ conda install jupyter_rfb
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - jupyter_rfb

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


(mescore) jupyter@instance-20231019-090835:~$ conda install -c conda-forge jupyter_rfb
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - jupyter_rfb

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by kushalkolar** [comment]
jupyter_rfb is only available via pip:

pip install jupyter_rfb

In your conda env. 

And then start jupyterlab again

**Comment by zhouyi0812** [comment]
Thank you!

I tried that and it worked...now I move forward with cnmf_eval. And just unable to import the necessary package.

from fastplotlib import ImageWidget, Plot, GridPlot
from fastplotlib.utils import get_colors
from fastplotlib.graphics.line_slider import LineSlider
from ipywidgets import VBox, IntSlider, Layout


---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[26], line 2
      1 from fastplotlib import ImageWidget, Plot, GridPlot
----> 2 from fastplotlib.utils import get_colors
      3 from fastplotlib.graphics.line_slider import LineSlider
      4 from ipywidgets import VBox, IntSlider, Layout

ImportError: cannot import name 'get_colors' from 'fastplotlib.utils' (/Users/yizhou/miniforge3/envs/caiman/lib/python3.11/site-packages/fastplotlib/utils/__init__.py)

Thank you!

**Comment by kushalkolar** [comment]
The component eval is a WIP, the other notebooks all work.

**Comment by kushalkolar** [comment]
Btw I'm curious what kind of performance you're getting with the
fastplotlib plots via Google cloud. Where are you located and where's the
Google cloud server located?

**Comment by zhouyi0812** [comment]
I think it works fine just as on the computer, but I just can't make jupyter_rfb work after multiple tries and switch to local.

the google cloud engine zone is us-central1-a and I am located at california.

**Comment by kushalkolar** [comment]
Did you install the Vulkan drivers on your Google cloud instance, see here:
https://github.com/fastplotlib/fastplotlib#graphics-drivers

**Comment by zhouyi0812** [comment]
Hello! 
I wonder when I use demo, our lab computer has space in the path that leads me fail to run the code, which I can't change.
set_parent_raw_data_path("/Users/Mourrain Lab/caiman_data/")

ValueError: Paths must only contain alphanumeric characters, hyphens ( - ), underscores ( _ ) or periods ( . )

And wonder if there is anyway that I can fix this? Thank you!!!!

**Comment by kushalkolar** [comment]
Nope, you'll need to use some other path.

**Comment by zhouyi0812** [comment]
Thank you!!

Can I ask another question? I try to plot the pnr with demo cnmfe, but there is a package error. Thank you!!

AttributeError                            Traceback (most recent call last)
Cell In[46], line 21
     17 mcorr_vids = [mcorr_movie.astype(np.float32) for i in range(4)]
     19 # sync the threshold image widget with the corr-pnr plot
     20 grid_plot_kwargs = {
---> 21     "controllers": [[iw_corr_pnr.plot["corr"].controller]*2]*2
     22 }
     24 iw_thres_movie = ImageWidget(
     25     mcorr_vids, 
     26     names=["> corr", "> pnr", "< corr", "< pnr"],
   (...)
     30     cmap="gnuplot2"
     31 )
     33 # display threshold of the spatially filtered movie

AttributeError: 'ImageWidget' object has no attribute 'plot'

**Comment by kushalkolar** [comment]
`ImageWidget` now only uses `gridplot` instead of `plot`.

**Comment by kushalkolar** [comment]
I updated the notebook according to the latest fastplotlib@main on github, the current version on main will be released in a few days.

**Comment by zhouyi0812** [comment]
Hello! I wonder after motion correction, the 5 movies are playing simultaneously and I have multiple parameters and big FOV. So I wonder if there is anyway that can zoom out the window for better view?

Or I have tried to code raw and motion correction side by side with the bottom to the next pairs, but the bottom just not working.

Thank you!!

import ipywidgets as widgets
from IPython.display import display, clear_output

paired_movies = list(zip(movies[::2], movies[1::2]))
paired_names = list(zip(subplot_names[::2], subplot_names[1::2]))

chunk_size = 1
movies_chunks = list(chunked(paired_movies, chunk_size))
subplot_names_chunks = list(chunked(paired_names, chunk_size))

def display_movies(chunk_idx):
    clear_output(wait=True)
    movies_group = movies_chunks[chunk_idx]
    subplot_names_group = subplot_names_chunks[chunk_idx]

    flat_movies = [movie for pair in movies_group for movie in pair]
    flat_names = [name for pair in subplot_names_group for name in pair]
    
    filt = {subplot_ix: lambda frame: high_pass_filter_space(frame, (3, 3)) for subplot_ix in range(len(flat_movies))}
    
    mcorr_iw_multiple = ImageWidget(
        data=flat_movies,
        window_funcs={"t": (np.mean, 3)},
        frame_apply=filt,
        names=flat_names,
        cmap="gnuplot2"
    )

    mcorr_iw_multiple.reset_vmin_vmax()
    mcorr_iw_multiple.show()
    display(button)

button = widgets.Button(description="Next")

def on_button_click(b):
    global current_chunk
    current_chunk += 1
    if current_chunk < len(movies_chunks):
        display_movies(current_chunk)
    else:
        clear_output(wait=True)
        print("All movie chunks displayed.")
        display(button)

button.on_click(on_button_click)

current_chunk = 0
display_movies(current_chunk)

**Comment by kushalkolar** [comment]
Are you in jupyterlab or jupyter notebook? We do not support jupyter notebook, only jupyter lab (it's almost the same as notebook, but you can have multiple nbs open in tabs). The reason I'm asking is because the buttons do not work in jupyter notebook as far as I know.

**Comment by zhouyi0812** [comment]
I am using the jupyter lab.

**Comment by kushalkolar** [comment]
Is the autoscale button not working?

**Comment by kushalkolar** [comment]
can you give me a screenshot of what you mean, I don't understand what you're trying to do

**Comment by zhouyi0812** [comment]
![Screenshot 2023-10-30 161835](https://github.com/nel-lab/mesmerize-core/assets/48576330/fe435c39-4b77-430a-b9cc-9584387b9658)
Sure! I am thinking about it too.
It works a little bit, but for too many parameters it looks not that obvious..  Thank you!

**Comment by kushalkolar** [comment]
What exactly is the issue?

**Comment by zhouyi0812** [comment]
So because each movie is too small and unable to see very clear about how the parameters impact on it. 
I was wondering if there is a way that could zoom out the whole view for all movies thus could see clearly. 
And if it would be better to plot 2 movies side by side with a bottom to check each pairs. 
Thanks!!!

**Comment by kushalkolar** [comment]
You mean increase the size of the canvas? There's a handle in the bottom right corner.

**Comment by zhouyi0812** [comment]
oh I see, thank you!! That's what I am looking for!

**Comment by kushalkolar** [comment]
I think you'll have an easier time if you watch the scipy talk, it has 20 minutes of demos on how to use fastplotlib: https://www.youtube.com/watch?v=Q-UJpAqljsU 

demo nbs: https://github.com/fastplotlib/fastplotlib-scipy2023 

Note that they are slightly outdated, you do not need to manually do the `with sidecar:` stuff anymore.

**Comment by zhouyi0812** [comment]
Hello! May I ask another question? Thank you!!

So after my motion correction, I tried to keep the uuid I want but was not able to run the code to remove others.

---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
File C:\Users\Public\anaconda3\envs\mescore\lib\site-packages\mesmerize_core\caiman_extensions\common.py:232, in CaimanDataFrameExtensions.remove_item(self, index, remove_data, safe_removal)
    231 try:
--> 232     rmtree(self._df.paths.get_batch_path().parent.joinpath(u))
    233 except PermissionError:

File C:\Users\Public\anaconda3\envs\mescore\lib\shutil.py:749, in rmtree(path, ignore_errors, onerror)
    748     return
--> 749 return _rmtree_unsafe(path, onerror)

File C:\Users\Public\anaconda3\envs\mescore\lib\shutil.py:619, in _rmtree_unsafe(path, onerror)
    618         except OSError:
--> 619             onerror(os.unlink, fullname, sys.exc_info())
    620 try:

File C:\Users\Public\anaconda3\envs\mescore\lib\shutil.py:617, in _rmtree_unsafe(path, onerror)
    616 try:
--> 617     os.unlink(fullname)
    618 except OSError:

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '\\Users\\Public\\anaconda3\\caiman_data\\mesmerize-cnmfe\\605976af-4e32-41a2-9a9b-c6f11fe1dbe1\\605976af-4e32-41a2-9a9b-c6f11fe1dbe1-data_endoscope_els__d1_128_d2_128_d3_1_order_F_frames_1000.mmap'

During handling of the above exception, another exception occurred:

PermissionError                           Traceback (most recent call last)
Cell In[32], line 3
      1 for i, row in df.iterrows():
      2     if row.uuid not in rows_keep:
----> 3         df.caiman.remove_item(row.uuid)

File C:\Users\Public\anaconda3\envs\mescore\lib\site-packages\mesmerize_core\caiman_extensions\_utils.py:55, in _index_parser.<locals>._parser(instance, *args, **kwargs)
     52 else:
     53     args = (index, *args[1:])
---> 55 return func(instance, *args, **kwargs)

File C:\Users\Public\anaconda3\envs\mescore\lib\site-packages\mesmerize_core\caiman_extensions\common.py:234, in CaimanDataFrameExtensions.remove_item(self, index, remove_data, safe_removal)
    232     rmtree(self._df.paths.get_batch_path().parent.joinpath(u))
    233 except PermissionError:
--> 234     raise PermissionError(
    235         "You do not have permissions to remove the "
    236         "output data for the batch item, aborting."
    237     )
    238 except FileNotFoundError:
    239     pass

PermissionError: You do not have permissions to remove the output data for the batch item, aborting.

**Comment by kushalkolar** [comment]
Windows does not allow deleting open memmap files, there's no way around it that I've been able to find.

When you want to delete files, what you can do is shutdown the notebook where memmap files are open and then use another notebook just for deleting the rows you don't want, and then continue.

**Comment by zhouyi0812** [comment]
Hello!! Thank you for your guidance!!!

When I tried to generate the correlation and pnr imaging. There is no video show with this code:
# to show the correlation and pnr images
iw_corr_pnr = ImageWidget(
    [corr, pnr], 
    names=["corr", "pnr"],
    vmin_vmax_sliders=True, 
    cmap="turbo"
)

# some slider stuff
iw_corr_pnr.vmin_vmax_sliders[0].description = "corr"
iw_corr_pnr.vmin_vmax_sliders[1].description = "pnr"

iw_corr_pnr.vmin_vmax_sliders[0].max = corr.max()
iw_corr_pnr.vmin_vmax_sliders[1].max = pnr.max()

# mcorr vids, we will display thresholded mcorr vids
mcorr_vids = [mcorr_movie.astype(np.float32) for i in range(4)]

# sync the threshold image widget with the corr-pnr plot
grid_plot_kwargs = {
    "controllers": [[iw_corr_pnr.gridplot["corr"].controller]*2]*2
}

iw_thres_movie = ImageWidget(
    mcorr_vids, 
    names=["> corr", "> pnr", "< corr", "< pnr"],
    vmin_vmax_sliders=True,
    # sync this with the corr-pnr plot
    grid_plot_kwargs=grid_plot_kwargs,
    cmap="gnuplot2"
)

# display threshold of the spatially filtered movie
def spatial_filter(frame):
    f = high_pass_filter_space(frame, (3, 3))
    return f


# threshold
def threshold(frame, mask):
    # optionally use spatial filter
    t = spatial_filter(frame)
    
    t = t.copy()
    
    t[mask] = t.min()
    
    return t

# dict of threshold lambda wrappers to set on ImageWidget
# this sets the frame_apply for each subplot
threshold_funcs = {
    0: lambda frame: threshold(frame, corr < iw_corr_pnr.vmin_vmax_sliders[0].value[0]),
    1: lambda frame: threshold(frame, pnr < iw_corr_pnr.vmin_vmax_sliders[1].value[0]),
    2: lambda frame: threshold(frame, corr > iw_corr_pnr.vmin_vmax_sliders[0].value[0]),
    3: lambda frame: threshold(frame, pnr > iw_corr_pnr.vmin_vmax_sliders[1].value[0])
}

# set the dict of lambda wrappers
iw_thres_movie.frame_apply = threshold_funcs

# hacky way to force the threshold plots to update
# when the corr pnr sliders move
def force_update_thresholds_plots(*args):
    iw_thres_movie.current_index = iw_thres_movie.current_index

iw_corr_pnr.vmin_vmax_sliders[0].observe(force_update_thresholds_plots)
iw_corr_pnr.vmin_vmax_sliders[1].observe(force_update_thresholds_plots)

force_update_thresholds_plots()

# iw_thres_movie.reset_vmin_vmax()
    
iw_corr_pnr.gridplot.canvas.set_logical_size(650, 300)
iw_thres_movie.gridplot.canvas.set_logical_size(650, 600)

vbox_content = []

# Check the output of iw_corr_pnr.show()
output_corr_pnr = iw_corr_pnr.show()
if output_corr_pnr is not None:
    vbox_content.append(output_corr_pnr)

# Check the output of iw_thres_movie.show()
output_thres_movie = iw_thres_movie.show()
if output_thres_movie is not None:
    vbox_content.append(output_thres_movie)

# Create and display the VBox
VBox(vbox_content)

And looks like this:

![Screenshot 2023-10-30 202724](https://github.com/nel-lab/mesmerize-core/assets/48576330/59ed48ad-29f6-4cb4-aed2-7034695f7f23)

So I try this code:
iw_corr_pnr.vmin_vmax_sliders[0].description = "corr"
iw_corr_pnr.vmin_vmax_sliders[1].description = "pnr"

iw_corr_pnr.vmin_vmax_sliders[0].max = corr.max()
iw_corr_pnr.vmin_vmax_sliders[1].max = pnr.max()
mcorr_vids = [mcorr_movie.astype(np.float32) for i in range(4)]

grid_plot_kwargs = {
    "controllers": [[iw_corr_pnr.gridplot["corr"].controller]*2]*2
}

iw_thres_movie = ImageWidget(
    mcorr_vids, 
    names=["> corr", "> pnr", "< corr", "< pnr"],
    vmin_vmax_sliders=True,
    grid_plot_kwargs=grid_plot_kwargs,
    cmap="gnuplot2"
)
iw_thres_movie.show()

which has video but without imaging after applying threshold.

![Screenshot 2023-10-30 202937](https://github.com/nel-lab/mesmerize-core/assets/48576330/5836a456-690c-4fb7-958e-a990de79bae0)

**Comment by kushalkolar** [comment]
Click the button ◐ to reset the vmin vmax sliders. 

FYI, we just released fastplotlib alpha 14 which uses a histogram LUT tool for vmin, vmax instead of the sliders, I will update the mesmerize nbs soon: https://github.com/fastplotlib/fastplotlib/pull/348#issue-1966373987

**Comment by kushalkolar** [comment]
BTW in the future if you can create new issues when you have a new issue that will be more organized than one long issue with many different topics.

**Comment by zhouyi0812** [comment]
After click  ◐, the second row is still a bit wired... Thank you!!!

 
![Screenshot 2023-10-30 204837](https://github.com/nel-lab/mesmerize-core/assets/48576330/5a2d8533-170c-4983-b311-83a751a04322)

**Comment by kushalkolar** [comment]
Yes the second row shows everything that is under the thresholds. Adjust the thresholds using the top two sliders, and then click the button to reset the vmin vmax again. As the notebook comment says: "reset vmin vmax when necessary!!!" :smile:

**Comment by kushalkolar** [comment]
@zhouyi0812 I'm updating the notebooks with respect to the latest release of fastplotlib and introducing mesmerize-viz. Here's how the corr-pr UI is meant to be used:

https://github.com/nel-lab/mesmerize-core/assets/9403332/4d0c4073-5816-4637-882f-90e0b9e954fd

**Comment by zhouyi0812** [comment]
Thank you so much for updating! It looks pretty cool!

I try to type the code from your video but some details may be missing and encounter error. I wonder which notebooks exactly it is? I look for the notebooks from mescore but it is not the latest one.

Thank you!

**Comment by kushalkolar** [comment]
It's in a branch, will be merged by Monday
