### ISSUE TITLE
TraitError: Setting min > max   when viz_cnmf = df.cnmf.viz() viz_cnmf.show()

### ISSUE THREAD

**Issue by qweasdf1354** [nel-lab/mesmerize-core#247]
**Hi author! I am using windows 10 and detecting the bigtif, which shape is 16000,512,600. I can run the mcorr and cnmf. however, i can not run the  viz_cnmf.show() due to the following error** 

```
`C:\Users\PS\miniforge3\envs\mescore\lib\site-packages\jupyter_client\session.py:721: UserWarning: Message serialization failed with:
Out of range float values are not JSON compliant
Supporting this message is deprecated in jupyter-client 7, please make sure your message is JSON-compliant
  content = self.pack(content)
---------------------------------------------------------------------------
TraitError                                Traceback (most recent call last)
Cell In[32], line 1
----> 1 viz_cnmf = df.cnmf.viz()
      2 viz_cnmf.show()

File c:\software\mesmerize-viz\mesmerize_viz\_cnmf.py:1193, in CNMFDataFrameVizExtension.viz(self, start_index, temporal_data_option, image_data_options, temporal_kwargs, reset_timepoint_on_change, input_movie_kwargs, image_widget_kwargs, data_grid_kwargs)
   1117 def viz(
   1118     self,
   1119     start_index: int = None,
   (...)
   1126     data_grid_kwargs: dict = None,
   1127 ):
   1128     """
   1129     Visualize CNMF output and other data columns such as behavior video (optional).
   1130 
   (...)
   1190         Example: `image_widget_kwargs={"cmap": "viridis"}`
   1191     """
-> 1193     container = CNMFVizContainer(
   1194         dataframe=self._dataframe,
   1195         start_index=start_index,
   1196         temporal_data_option=temporal_data_option,
   1197         image_data_options=image_data_options,
   1198         temporal_kwargs=temporal_kwargs,
   1199         reset_timepoint_on_change=reset_timepoint_on_change,
   1200         input_movie_kwargs=input_movie_kwargs,
   1201         image_widget_kwargs=image_widget_kwargs,
   1202         data_grid_kwargs=data_grid_kwargs,
   1203 
   1204     )
   1206     return container

File c:\software\mesmerize-viz\mesmerize_viz\_cnmf.py:583, in CNMFVizContainer.__init__(self, dataframe, start_index, temporal_data_option, image_data_options, temporal_kwargs, reset_timepoint_on_change, input_movie_kwargs, image_widget_kwargs, data_grid_kwargs)
    580 self._cnmf_obj: CNMF = None
    582 data_arrays = self._get_row_data(index=start_index)
--> 583 self._set_data(data_arrays)
    585 self._set_params_text_area(index=start_index)
    587 self._widget = None

File c:\software\mesmerize-viz\mesmerize_viz\_cnmf.py:788, in CNMFVizContainer._set_data(self, data_arrays)
    784 # current state of CNMF object
    785 # this can be different from the one in the dataframe if the user uses eval
    786 self._cnmf_obj: CNMF = data_arrays["cnmf_obj"]
--> 788 self._eval_controller.set_limits(self._cnmf_obj)

File c:\software\mesmerize-viz\mesmerize_viz\_cnmf.py:228, in EvalController.set_limits(self, cnmf_obj)
    226 # allow 100 steps
    227 self._widgets[metric][ui_element].step = np.ptp(metric_array) / 100
--> 228 self._widgets[metric][ui_element].min = metric_array.min()
    229 self._widgets[metric][ui_element].max = metric_array.max()
    230 self._widgets[metric][ui_element].value = cnmf_obj.params.get_group("quality")[metric]

File ~\miniforge3\envs\mescore\lib\site-packages\traitlets\traitlets.py:718, in TraitType.__set__(self, obj, value)
    716     raise TraitError('The "%s" trait is read-only.' % self.name)
    717 else:
--> 718     self.set(obj, value)

File ~\miniforge3\envs\mescore\lib\site-packages\traitlets\traitlets.py:691, in TraitType.set(self, obj, value)
    690 def set(self, obj: HasTraits, value: S) -> None:
--> 691     new_value = self._validate(obj, value)
    692     assert self.name is not None
    693     try:

File ~\miniforge3\envs\mescore\lib\site-packages\traitlets\traitlets.py:726, in TraitType._validate(self, obj, value)
    724     value = self.validate(obj, value)
    725 if obj._cross_validation_lock is False:
--> 726     value = self._cross_validate(obj, value)
    727 return t.cast(G, value)

File ~\miniforge3\envs\mescore\lib\site-packages\traitlets\traitlets.py:732, in TraitType._cross_validate(self, obj, value)
    730 if self.name in obj._trait_validators:
    731     proposal = Bunch({"trait": self, "value": value, "owner": obj})
--> 732     value = obj._trait_validators[self.name](obj, proposal)
    733 elif hasattr(obj, "_%s_validate" % self.name):
    734     meth_name = "_%s_validate" % self.name

File ~\miniforge3\envs\mescore\lib\site-packages\traitlets\traitlets.py:1243, in EventHandler.__call__(self, *args, **kwargs)
   1241 """Pass `*args` and `**kwargs` to the handler's function if it exists."""
   1242 if hasattr(self, "func"):
-> 1243     return self.func(*args, **kwargs)
   1244 else:
   1245     return self._init_call(*args, **kwargs)

File ~\miniforge3\envs\mescore\lib\site-packages\ipywidgets\widgets\widget_float.py:46, in _BoundedFloat._validate_min(self, proposal)
     44 min = proposal['value']
     45 if min > self.max:
---> 46     raise TraitError('Setting min > max')
     47 if min > self.value:
     48     self.value = min

TraitError: Setting min > max`
```

**I do not understand the min and max mean, so i could not deal with by myself. Could you help me?**

**the following is the warning when i run the viz.show above the error, i do not know whether it is related to the error.**

```
`C:\Users\PS\miniforge3\envs\mescore\lib\site-packages\ipydatagrid\datagrid.py:460:` UserWarning: Index name of 'index' is not round-trippable.
  schema = pd.io.json.build_table_schema(dataframe)
c:\software\mesmerize-viz\mesmerize_viz\_cnmf.py:620: RuntimeWarning: overflow encountered in scalar multiply
  size = rcm.shape[0] * rcm.shape[1] * rcm.shape[2]
C:\Users\PS\miniforge3\envs\mescore\lib\site-packages\fastplotlib\graphics\_features\_base.py:34: UserWarning: converting float64 array to float32
  warn(f"converting {array.dtype} array to float32")`
```

**Comment by kushalkolar** [comment]
git pull the latest mesmerize-viz, this was fixed a few days ago.

**Comment by qweasdf1354** [comment]
Nice to see you kushal! I will try it soon

**Comment by qweasdf1354** [comment]
Awsome! It works!!

**Comment by qweasdf1354** [comment]
Hi kushal! 
in the eval paramether panel, the first to raw maybe the SNR, has the error below, it not affect me, but i want to let you know

`[Open Browser Console for more detailed log - Double click to close this message]
Failed to create view for 'FloatSliderView' from module '@jupyter-widgets/controls' with model 'FloatSliderModel' from module '@jupyter-widgets/controls'
Error: noUiSlider: 'step' is not numeric.
    at Object.N [as t] (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/345.17494fea1ff555b26294.js?v=17494fea1ff555b26294:1:17628)
    at http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/345.17494fea1ff555b26294.js?v=17494fea1ff555b26294:1:23416
    at Array.forEach ()
    at W (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/345.17494fea1ff555b26294.js?v=17494fea1ff555b26294:1:23364)
    at Object.G [as create] (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/345.17494fea1ff555b26294.js?v=17494fea1ff555b26294:1:38320)
    at Re.createSlider (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/495.79062b4ce5ec7920dcb1.js?v=79062b4ce5ec7920dcb1:1:38924)
    at Re.render (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/495.79062b4ce5ec7920dcb1.js?v=79062b4ce5ec7920dcb1:1:37372)
    at http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1:2959
    at async Promise.all (index 1)`

`[Open Browser Console for more detailed log - Double click to close this message]
Failed to create view for 'FloatSliderView' from module '@jupyter-widgets/controls' with model 'FloatSliderModel' from module '@jupyter-widgets/controls'
Error: noUiSlider: 'step' is not numeric.
    at Object.N [as t] (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/345.17494fea1ff555b26294.js?v=17494fea1ff555b26294:1:17628)
    at http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/345.17494fea1ff555b26294.js?v=17494fea1ff555b26294:1:23416
    at Array.forEach ()
    at W (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/345.17494fea1ff555b26294.js?v=17494fea1ff555b26294:1:23364)
    at Object.G [as create] (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/345.17494fea1ff555b26294.js?v=17494fea1ff555b26294:1:38320)
    at Re.createSlider (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/495.79062b4ce5ec7920dcb1.js?v=79062b4ce5ec7920dcb1:1:38924)
    at Re.render (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/495.79062b4ce5ec7920dcb1.js?v=79062b4ce5ec7920dcb1:1:37372)
    at http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1:2959
    at async Promise.all (index 1)
0.9903962485552973
rval_thr
`

**Comment by kushalkolar** [comment]
> Hi kushal! in the eval paramether panel, the first to raw maybe the SNR, has the error below, it not affect me, but i want to let you know
> 
> ```
> [Open Browser Console for more detailed log - Double click to close this message]
> Failed to create view for 'FloatSliderView' from module '@jupyter-widgets/controls' with model 'FloatSliderModel' from module '@jupyter-widgets/controls'
> Error: noUiSlider: 'step' is not numeric.
>     at Object.N [as t] (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/345.17494fea1ff555b26294.js?v=17494fea1ff555b26294:1:17628)
>     at http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/345.17494fea1ff555b26294.js?v=17494fea1ff555b26294:1:23416
>     at Array.forEach ()
>     at W (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/345.17494fea1ff555b26294.js?v=17494fea1ff555b26294:1:23364)
>     at Object.G [as create] (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/345.17494fea1ff555b26294.js?v=17494fea1ff555b26294:1:38320)
>     at Re.createSlider (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/495.79062b4ce5ec7920dcb1.js?v=79062b4ce5ec7920dcb1:1:38924)
>     at Re.render (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/495.79062b4ce5ec7920dcb1.js?v=79062b4ce5ec7920dcb1:1:37372)
>     at http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1:2959
>     at async Promise.all (index 1)`
> 
> `[Open Browser Console for more detailed log - Double click to close this message]
> Failed to create view for 'FloatSliderView' from module '@jupyter-widgets/controls' with model 'FloatSliderModel' from module '@jupyter-widgets/controls'
> Error: noUiSlider: 'step' is not numeric.
>     at Object.N [as t] (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/345.17494fea1ff555b26294.js?v=17494fea1ff555b26294:1:17628)
>     at http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/345.17494fea1ff555b26294.js?v=17494fea1ff555b26294:1:23416
>     at Array.forEach ()
>     at W (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/345.17494fea1ff555b26294.js?v=17494fea1ff555b26294:1:23364)
>     at Object.G [as create] (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/345.17494fea1ff555b26294.js?v=17494fea1ff555b26294:1:38320)
>     at Re.createSlider (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/495.79062b4ce5ec7920dcb1.js?v=79062b4ce5ec7920dcb1:1:38924)
>     at Re.render (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/495.79062b4ce5ec7920dcb1.js?v=79062b4ce5ec7920dcb1:1:37372)
>     at http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1:2959
>     at async Promise.all (index 1)
> 0.9903962485552973
> rval_thr
> ```

restart your jupyterlab server

**Comment by qweasdf1354** [comment]
Thanks!

**Comment by qweasdf1354** [comment]
Thanks! Kushal! I got this fixed!
