### ISSUE TITLE
How to get z score of raw and deltaF/F

### ISSUE THREAD

**Issue by qweasdf1354** [nel-lab/mesmerize-core#248]
Hi, author! you teach me how to get the deltaF/F, i got it. However, i notice there can extract z score, I do not understand how to got it. could you help me?

**Comment by kushalkolar** [comment]
See the docstring for cnmf.viz, you can give different keyword arguments to
temporal data options

**Comment by qweasdf1354** [comment]
Thanks, I will read it soon!

**Comment by kushalkolar** [comment]
This will give you what people call "zscore" https://tslearn.readthedocs.io/en/latest/gen_modules/preprocessing/tslearn.preprocessing.TimeSeriesScalerMeanVariance.html
