### ISSUE TITLE
Could I manually set the eval? using the code

### ISSUE THREAD

**Issue by qweasdf1354** [nel-lab/mesmerize-core#249]
Hi author!, Could I manually set the eval using the code? because i am worrying about the 16000,512,600 could not be viz.show. the optional way is to set the eval value manually. I notice this week you are very busy. I am sorry to bother you to much. If you have time, please let me know. Thanks a lot!

**Comment by kushalkolar** [comment]
I don't understand what you mean

**Comment by qweasdf1354** [comment]
I want to manually set the SNR or cnn parameter in the eval, if I can not open the viz

**Comment by qweasdf1354** [comment]
It now is not need. I have done and open the VIZ

**Comment by kushalkolar** [comment]
> I want to manually set the SNR or cnn parameter in the eval, if I can not open the viz

I think this might be what you want: 
https://mesmerize-core.readthedocs.io/en/latest/api/cnmf.html#mesmerize_core.CNMFExtensions.run_eval

**Comment by qweasdf1354** [comment]
Yes, Kushal! Thanks!
