### ISSUE TITLE
TypeError: Cannot convert '<H' to wgpu format. You should provide data with a different dtype.

### ISSUE THREAD

**Issue by santicolom** [nel-lab/mesmerize-core#252]
https://github.com/nel-lab/mesmerize-core/blob/master/notebooks/cnmfe.ipynb

Hello, I was running this code after having followed the tutorials for installing mesmerize. I had an error that I can't seem to fix.

Code:

# create a slider for gSig_filt
slider_gsig_filt = IntSlider(value=3, min=1, max=33, step=2,  description="gSig_filt")

def apply_filter(frame):
    # read slider value
    gSig_filt = (slider_gsig_filt.value, slider_gsig_filt.value)
    
    # apply filter
    return high_pass_filter_space(frame, gSig_filt)

# we can use frame_apply feature of `ImageWidget` to apply 
# the filter before displaying frames
funcs = {
    # data_index: function
    1: apply_filter  # filter shown on right plot, index 1
}

# input movie will be shown on left, filtered on right
iw_gs = fpl.ImageWidget(
    data=[input_movie, input_movie.copy()],
    frame_apply=funcs,
    names=["raw", "filtered"],
    grid_plot_kwargs={"size": (1200, 600)},
    cmap="gnuplot2"
)

def force_update(*args):
    # kinda hacky but forces the images to update 
    # when the gSig_filt slider is moved
    iw_gs.current_index = iw_gs.current_index
    iw_gs.reset_vmin_vmax()

iw_gs.reset_vmin_vmax()
    
slider_gsig_filt.observe(force_update, "value")

VBox([iw_gs.show(), slider_gsig_filt])

Error:

WARNING:wgpu:	EGL surface: -srgb
WARNING:wgpu:No config found!
WARNING:wgpu:EGL says it can present to the window but not natively
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[24], line 19
     13 funcs = {
     14     # data_index: function
     15     1: apply_filter  # filter shown on right plot, index 1
     16 }
     18 # input movie will be shown on left, filtered on right
---> 19 iw_gs = fpl.ImageWidget(
     20     data=[input_movie, input_movie.copy()],
     21     frame_apply=funcs,
     22     names=["raw", "filtered"],
     23     grid_plot_kwargs={"size": (1200, 600)},
     24     cmap="gnuplot2"
     25 )
     27 def force_update(*args):
     28     # kinda hacky but forces the images to update 
     29     # when the gSig_filt slider is moved
     30     iw_gs.current_index = iw_gs.current_index

File ~\anaconda3\envs\mescore\lib\site-packages\fastplotlib\widgets\image.py:558, in ImageWidget.__init__(self, data, dims_order, slider_dims, window_funcs, frame_apply, grid_shape, names, grid_plot_kwargs, histogram_widget, **kwargs)
    556 frame = self._process_indices(d, slice_indices=self._current_index)
    557 frame = self._process_frame_apply(frame, data_ix)
--> 558 ig = ImageGraphic(frame, name="image_widget_managed", **kwargs)
    559 subplot.add_graphic(ig)
    560 subplot.name = name

File ~\anaconda3\envs\mescore\lib\site-packages\fastplotlib\graphics\image.py:276, in ImageGraphic.__init__(self, data, vmin, vmax, cmap, filter, isolated_buffer, *args, **kwargs)
    273 if (vmin is None) or (vmax is None):
    274     vmin, vmax = quick_min_max(data)
--> 276 texture = pygfx.Texture(buffer_init, dim=2)
    278 geometry = pygfx.Geometry(grid=texture)
    280 self.cmap = ImageCmapFeature(self, cmap)

File ~\anaconda3\envs\mescore\lib\site-packages\pygfx\resources\_texture.py:77, in Texture.__init__(self, data, dim, size, format, colorspace, generate_mipmaps)
     75 self._store.nbytes = mem.nbytes
     76 self._store.size = self._size_from_data(mem, dim, size)
---> 77 subformat = get_item_format_from_memoryview(mem)
     78 if subformat is None:
     79     raise ValueError(
     80         f"Unsupported dtype/format for texture data: {mem.format}"
     81     )

File ~\anaconda3\envs\mescore\lib\site-packages\pygfx\resources\_base.py:52, in get_item_format_from_memoryview(mem)
     49 format = STRUCT_FORMAT_ALIASES.get(format, format)
     51 if format not in FORMAT_MAP:
---> 52     raise TypeError(
     53         f"Cannot convert {format!r} to wgpu format. You should provide data with a different dtype."
     54     )
     55 return FORMAT_MAP[format]

TypeError: Cannot convert '<H' to wgpu format. You should provide data with a different dtype.

Please help and thank you.

**Comment by kushalkolar** [comment]
GPUs only support certain dtypes, if you use ".astype(np.float32)" on the
input data array it'll work.

**Comment by santicolom** [comment]
Thank you! That worked and I can now see the first visualizations.
