### ISSUE TITLE
Evaluate Bleaching on the movie

### ISSUE THREAD

**Issue by zhouyi0812** [nel-lab/mesmerize-core#258]
Hello,
I want to see if my movie is bleaching and trying to get a graph for the mean project on each frames or in between certain frames.
I am not sure how I could integrate with the mes platform.
Or, how can I get the numbers for mean projection on each frame?
Thank you!!

**Comment by kushalkolar** [comment]
Memmaps are arrays.

You would benefit from a basic tutorial on numpy:
https://youtu.be/ZB7BZMhfPgk?si=wytdpIYIdQwn-JlI

**Comment by zhouyi0812** [comment]
I think I figure out this and want to post my code here if someone needs it

frame_means = []

for frame in mcorr_movie:
    frame_mean = frame.mean()
    frame_means.append(frame_mean)

frame_means = mcorr_movie.mean(axis=(1, 2))
frame_means
num_data_points = frame_means.shape[0]

print(f"Number of data points in frame_means: {num_data_points}")
plt.plot(frame_means)

plt.title('Mean Intensity of Each Frame')
plt.xlabel('Frame Number')
plt.ylabel('Mean Intensity')
plt.show()
