### ISSUE TITLE
Getting denoised dF/F

### ISSUE THREAD

**Issue by kingmiaomiao** [nel-lab/mesmerize-core#260]
Hi,
I'm trying to understand the df/f calculation, and when (or if) residuals are used (this is related to the [message I posted on Gitter](https://matrix.to/#/!FQZGCADfyiEEmhgyVt:gitter.im/$nAFfSBwtjf1T-u9A8jAhRcaMRcteZijFLaUsWtCKEHc?via=gitter.im)). 
When I call `df.iloc[1].cnmf.run_detrend_dfof(use_residuals = False)`, mesmerize then calls [`estimates.detrend_df_f`](https://github.com/nel-lab/mesmerize-core/blob/d26857d8c529b65d24114941011257a64dd635e4/mesmerize_core/caiman_extensions/cnmf.py#L627), which eventually goes to `detrend_df_f` in [`CaImAn/caiman/source_extraction/cnmf/utilities.py`](https://github.com/flatironinstitute/CaImAn/blob/9b0b79ca61f20ce93259b9833e1fe18e26d4e086/caiman/source_extraction/cnmf/utilities.py#L459C5-L459C17). 
However, before that, [the code in estimates.py](https://github.com/flatironinstitute/CaImAn/blob/9b0b79ca61f20ce93259b9833e1fe18e26d4e086/caiman/source_extraction/cnmf/estimates.py#L777) seem to ignore the flag `use_residuals = False`:
```
        if self.C is None or self.C.shape[0] == 0:
            logging.warning("There are no components for DF/F extraction!")
            return self

        if use_residuals:
            if self.R is None:
                if self.YrA is None:
                    R = None
                else:
                    R = self.YrA
            else:
                R = self.R
        else:
            R = None

        self.F_dff = detrend_df_f(self.A, self.b, self.C, self.f, self.YrA,
                                  quantileMin=quantileMin,
                                  frames_window=frames_window,
                                  flag_auto=flag_auto, use_fast=use_fast,
                                  detrend_only=detrend_only)
        return self
```
Could you explain what happens there, and how to get a denoised df/f, without the residuals? 
What should I change to my code below?
 ```
df.iloc[1].cnmf.run_detrend_dfof(use_residuals = False)
cnmf_data = df.iloc[1].cnmf.get_output()
F_dff = cnmf_data.estimates.F_dff
```
Right now the df/f does not seem to be denoised. 
![image](https://github.com/nel-lab/mesmerize-core/assets/8517447/d6767192-5a31-4045-ac1e-f52b379d67f5)

Thanks in advance for your help!

**Comment by kushalkolar** [comment]
this is more of a caiman question than mesmerize question, @EricThomson might have an answer

**Comment by EricThomson** [comment]
Yes there is a `use_residual` keyword that currently has no effect when calculating `dff`. See https://github.com/flatironinstitute/CaImAn/issues/1188

**Comment by vncntprvst** [comment]
Thanks @EricThomson for pointing to that open issue, and working on solving this bug :)
I'll comment on the CaImAn repo's thread for that issue.

**Comment by kingmiaomiao** [comment]
Thank you! In the meantime, can I just change this one line in CaImAn, when estimates calls `detrend_df_f`, replacing `self.YrA` with  `R`? 
I will update caiman when you push the fixed code. I assume you will create a new release?

**Comment by EricThomson** [comment]
That's the fix :smile: it's currently in a PR that should be in the next release.

**Comment by kingmiaomiao** [comment]
It works!! Thank you!!!
