### ISSUE TITLE
Issue with cnmfe notebook with fastplotlib

### ISSUE THREAD

**Issue by JohnStout** [nel-lab/mesmerize-core#261]
Running through mescore per/corr image display section in your CNMFE notebook. Running into this error. Checked this code with an older version of mescore and this isn't an issue. Looks like it's related to fastplotlib?

Thank you!
-John

<img width="1084" alt="Screenshot 2023-12-23 at 3 26 57 PM" src="https://github.com/nel-lab/mesmerize-core/assets/46092030/f78bd60d-9151-43e5-b061-d3fd806ef85e">

**Comment by kushalkolar** [comment]
https://github.com/fastplotlib/fastplotlib/releases/tag/v0.1.0.a16

**Comment by kushalkolar** [comment]
Sorry for the succint reply, my availability is spotty during the holidays. If you replace `"controllers": [[iw_corr_pnr...` with `"controller_types": [[iw_corr_pnr...` in line 14 it should work. 

We usually make note of major breaking changes in the release notes as linked above.

**Comment by JohnStout** [comment]
Thanks Kushal, happy holidays!
-John
