### ISSUE TITLE
Question about 1p data processing

### ISSUE THREAD

**Issue by zhouyi0812** [nel-lab/mesmerize-core#262]
Hello!
Thank you very much for your time and help!
I wonder do you have any suggestion when processing the df/f. I have cells recording and I found their firing pattern is quiet interesting: for some movies many cells are firing at the same time. So I want to quantify these difference.
I used want to deconvolved the trace and use spike statistics but you told me there is no ground truth data, so I wonder if you have and idea that I could conduct this analysis?
Thank you!!

**Comment by kushalkolar** [comment]
@EricThomson

**Comment by EricThomson** [comment]
Yes good to analyze traces rather than spikes with 1p data. 

In terms of what analysis to do, this is a big question as we discussed some [here](https://github.com/flatironinstitute/CaImAn/discussions/1208). Maybe follow up there with more specifics.

**Comment by kushalkolar** [comment]
I'm assuming your question has been answered, closing.
