### ISSUE TITLE
install mescore on computer

### ISSUE THREAD

**Issue by zhouyi0812** [nel-lab/mesmerize-core#266]
Hello! I was setting up another computer for mescore.
I download the miniforge for all users in a public computer. However when log in with an individual user account and install the mescore with mamba create -n mescore -c conda-forge mesmerize-core. There is an error say missing require package for caiman, mescore-viz and tensorflow.
I wonder if I should install the miniforge for one user only
Thank you!

**Comment by kushalkolar** [comment]
I don't know how conda works across user accounts, maybe just use one user
account for everyone?

**Comment by zhouyi0812** [comment]
Ok! Thank you! I have fixed it buy set conda for one user only
