### ISSUE TITLE
How to adjust n_processes in mescore

### ISSUE THREAD

**Issue by zhouyi0812** [nel-lab/mesmerize-core#269]
Hello!
I wonder if I could change the n_processes in mescore? And what is the disadvantage if I reduce the n_processes for higher speed?
Also, if I have a general pnr and corr, if it is possible that I could set the number in parameters rather than adjust each time?
Thank you!

When you use algo="cnmfe", it basically forces the following parameters:

"method_init": "corr_pnr",
"n_processes": n_processes,
"only_init": True,  # for 1p
"center_psf": True,  # for 1p
"normalize_init": False,  # for 1p

**Comment by kushalkolar** [comment]
> Hello! I wonder if I could change the n_processes in mescore? And what is the disadvantage if I reduce the n_processes for higher speed?

https://github.com/nel-lab/mesmerize-core/issues/205#issuecomment-1574585472

> Also, if I have a general pnr and corr, if it is possible that I could set the number in parameters rather than adjust each time? Thank you!

Yes
