### ISSUE TITLE
run_eval output

### ISSUE THREAD

**Issue by zhouyi0812** [nel-lab/mesmerize-core#270]
Hello!
I adjusted the run_eval according to mescore, but the evaluation output is 'nonetype' 
How should I adjust it?
Thank you very much!

min_SNR = 3            # SNR threshold
rval_thr = 0.85    # spatial correlation threshold

quality_params = {'min_SNR': min_SNR,
                  'rval_thr': rval_thr,
                  'use_cnn': False}

index = 1
eval = df.iloc[index].cnmf.run_eval(quality_params)

#print('*****')
#print(f"Number accepted: {(len(df.iloc[index].cnmf.get_good_components))}")
#print(f"Number rejected: {len(df.iloc[index].cnmf.get_bad_components)}")

**Comment by kushalkolar** [comment]
From the docstring:

```
Run component evaluation. This basically changes the indices for good and bad components.
```

**Comment by zhouyi0812** [comment]
So the output of ixs_good = df.iloc[index].cnmf.get_good_components() already represents the good components right?
If so, what is the evaluation parameters behind?

**Comment by kushalkolar** [comment]
The caiman docs has some stuff on the eval components:

https://caiman.readthedocs.io/en/latest/Getting_Started.html#component-evaluation

**Comment by zhouyi0812** [comment]
Thank you!
But if I want to change it maybe to a higher value, can I follow the steps above?
In that case, how to present accepted components and reject components?

**Comment by kushalkolar** [comment]
Why not just use the visualization in mesviz you can interactively set all the eval params

**Comment by zhouyi0812** [comment]
Because there are too many movies, I think it should be helpful after I check certain number of movies and find a common use parameters for the rest and just looping

**Comment by zhouyi0812** [comment]
Also, I found there is a line connect two components for some cases.

![Screenshot 2024-02-06 161819](https://github.com/nel-lab/mesmerize-core/assets/48576330/ccb57950-7e1a-4df6-adb7-abed6a4ea45a)

**Comment by kushalkolar** [comment]
That's one component

**Comment by zhouyi0812** [comment]
If I don't think that's the one component, if I could delete directly from the evaluation panel?
Thank you!

**Comment by kushalkolar** [comment]
You probably have to increase min_corr to split it.
