### ISSUE TITLE
 Issues with mesmerize Execution: Missing Packages in Active Conda Environment

### ISSUE THREAD

**Issue by Tepps-ps** [nel-lab/mesmerize-core#272]
After installing mesmerize and its dependencies in a Conda environment, I encounter multiple warnings and a ModuleNotFoundError when attempting to launch mesmerize. Despite successful installation (verified through conda list), mesmerize reports that it cannot find caiman, tensorflow,  tslearn, and h5py not being found. Any advice on further steps or potential solutions would be greatly appreciated.

Environment:
OS: Windows 10
Conda version: 23.11.0
Python version: 3.10.13
Installed packages: caiman 1.10.2
                               tensorflow 2.10.0
                               tslearn 0.6.3
                               h5py 3.9.0

**Comment by kushalkolar** [comment]
What installation instructions did you follow?

**Comment by Tepps-ps** [comment]
I followed the installation instructions with the following steps:

conda install -c conda-forge mamba
mamba create -n mescore -c conda-forge mesmerize-core
mamba activate mescore
caimanmanager install
pip install "fastplotlib[notebook]"

**Comment by kushalkolar** [comment]
If you activate the environment and launch jupyterlab do the demo notebooks run?

**Comment by Tepps-ps** [comment]
The demo notebooks can be run, but the kernel crashes when running command create a slider for gSig_filt. The kernel dies right after a warning about data type conversion (float64 to float32) and restarts automatically. 
![Uploading screenshot (13).png…]()

**Comment by kushalkolar** [comment]
I notice you deleted a comment about the kernel dieing (we get notifications about everything, you don't have to be shy :P ). Either you have a GPU with insufficient RAM or you don't have a modern GPU.

**Comment by Tepps-ps** [comment]
Thank you for finding the comment! Updating the driver resolved the issue with the kernel crashing. However, when I executed the command 'df.iloc[0].caiman.run(),' I encountered an error stating, 'ValueError: need at most 63 handles, got a sequence of length 65.' The process has been running for over a dozen hours. I'm using Windows; doesn't this seem like an excessively long time?

**Comment by kushalkolar** [comment]
I need to see the full traceback

**Comment by Tepps-ps** [comment]
![sc 2024-02-17 113524](https://github.com/nel-lab/mesmerize-core/assets/144749708/9b55cac9-d175-408f-b027-84ef96b1c17d)
Here is the traceback. It has been more than 12 hours since running the command.

**Comment by kushalkolar** [comment]
it says motion correction finished successfully?

**Comment by Tepps-ps** [comment]
Yes, but still running..

**Comment by kushalkolar** [comment]
Send a keyboard interrupt

**Comment by Tepps-ps** [comment]
After keyboard interrupt, an error log about multiprocessing was displayed.
![sc 2024-02-17 135750](https://github.com/nel-lab/mesmerize-core/assets/144749708/94e4ed41-842d-4e97-b6b3-0086dcef757b)
![sc 2024-02-17 135832](https://github.com/nel-lab/mesmerize-core/assets/144749708/baaa7e9a-460d-4d75-8ae4-1be1ae00e965)
![sc 2024-02-17 135918](https://github.com/nel-lab/mesmerize-core/assets/144749708/b7661f73-5a50-4374-84b4-60626db81ccb)
![sc 2024-02-17 135952](https://github.com/nel-lab/mesmerize-core/assets/144749708/aa8e211b-e6d5-4dc7-a43f-48ac971facdc)

**Comment by kushalkolar** [comment]
yea that happens when you do a keyboard interrupt, are you able to view the results? What are the dims of the input movie?

**Comment by Tepps-ps** [comment]
I'm unable to view any results. I used  caimadata examples named 'data_endoscope'. It consists of 1000 frames, 128x128 pixels and a 16-bit depth.

**Comment by kushalkolar** [comment]
> I'm unable to view any results.

Can you please elaborate, what did you do and what do you get?

**Comment by Tepps-ps** [comment]
Basically, the commands prepared in advance in the demo notebook 'cnmfe.ipynb' are executed in order from the top.
While running the CaIman run command  (df.iloc[0].caiman.run()) for motion correction on the first item in the DataFrame, the Jupyter Notebook remained in the "running" state for over 12 hours, even though the log output indicated that the process had finished successfully with the message mc finished successfully!. The DataFrame's first item (index 0) was configured with the following parameters:

- Algorithm: mcorr (motion correction)
- Item name: data_endoscope
- Input movie path: example_movies\data_endoscope.tif
- Parameters: {'gSig_filt': (3, 3), 'pw_rigid': True, 'max_shifts': (5, 5), 'strides': (48, 48), 'overlaps': (24, 24),,,

In the output directory, files associated with the UUID d30a6e53-f727-4fee-97eb-c69b1ab8a027 were generated, which suggests that some level of processing was completed. However, a ValueError indicating that more than 63 handles were being waited on was encountered, which may be related to the hangup.

**Comment by Tepps-ps** [comment]
Sorry for bothering you. Here is screenshot of  files are present in the uuid dir. And I also shared the results of running the  command `df = df.caiman.reload_from_disk()` in the Jupytert lab. I thought that if `df.iloc[0].caiman.run()` completed successfully, some value would be added in index[0]output  is this correct?
![Screenshot 2024-02-20 141419](https://github.com/nel-lab/mesmerize-core/assets/144749708/48f58afc-af65-4f4e-87a0-5188b9368f99)
![Screenshot 2024-02-20 141555](https://github.com/nel-lab/mesmerize-core/assets/144749708/25d718f2-dd5a-4944-97f7-0b5660404882)
![Screenshot 2024-02-20 141715](https://github.com/nel-lab/mesmerize-core/assets/144749708/e2f7ba58-5798-4c09-b692-cc68988e896c)

**Comment by kushalkolar** [comment]
From this it seems like multiprocessing on Windows doesn't work with more than 60 processes: https://github.com/scikit-learn/scikit-learn/issues/13354

You can limit the number of processes spawned to less than 60, see this: https://github.com/nel-lab/mesmerize-core/issues/205#issuecomment-1574585472

**Comment by Tepps-ps** [comment]
Thank you for your prompt and courteous response (I apologize for the delayed reply). The issue was resolved by limiting the number of processes spawned to less than 60.
