### ISSUE TITLE
problem with caiman.remove_item

### ISSUE THREAD

**Issue by Jorgenhoyer** [nel-lab/mesmerize-core#273]
I am having problems removing items from the dataframe. 

Using 

`caiman.remove_item("uuid", remove_data=True, safe_removal=True) `

sets the entire dataframe to none.

Am I missing something here or is there an issue with the command?

**Comment by kushalkolar** [comment]
The uuid argument has to be a uuid

**Comment by Jorgenhoyer** [comment]
It is a uuid

**Comment by kushalkolar** [comment]
Can you provide more info, screenshot of the dataframe before and after? And the exact removal command you used.

**Comment by Jorgenhoyer** [comment]
now worries. problem solved using index. caiman.remove_item(index = n, remove_data=True, safe_removal=True) where n is: 0,1,2,3...n
