### ISSUE TITLE
extract mcorr movie as tiff

### ISSUE THREAD

**Issue by Jorgenhoyer** [nel-lab/mesmerize-core#274]
Is there a way to extract the motion corrected movies and save them as tiff?

**Comment by kushalkolar** [comment]
What are you actually trying to do? The memmaps behave just like any other numpy array and are much nicer to work with than tiff files (lazy loading, etc.)

**Comment by Jorgenhoyer** [comment]
Yes, thats true. But I need the mcorr video for use outside of mesmerize.

**Comment by kushalkolar** [comment]
You can write to a tiff file using the `tifffile` library, create a `TiffWriter` object and write to it frame-by-frame. I don't have it off the top of my head but it's easy to figure out :)

**Comment by Jorgenhoyer** [comment]
Ok, thanks:)
