### ISSUE TITLE
demo for downstream analysis

### ISSUE THREAD

**Issue by zhouyi0812** [nel-lab/mesmerize-core#277]
Hello!

I wonder do you have demo for the downstream analysis/project management like the GUI from the paper?

Thank you!

**Comment by zhouyi0812** [comment]
Hello!
I am trying the code with data in from your github repo.
This function doesn't work and I can't find out which package I should install.
Thank you!

![image](https://github.com/nel-lab/mesmerize-core/assets/48576330/ba533ff8-b9e2-404b-a180-1f28596ef99e)

**Comment by kushalkolar** [comment]
That's from the old mesmerize which we no longer support.

**Comment by kushalkolar** [comment]
My strong recommendation would be to use pynapple for all downstream analysis: https://github.com/pynapple-org/pynapple
