### ISSUE TITLE
widget wont load

### ISSUE THREAD

**Issue by blogeman** [nel-lab/mesmerize-core#278]
The visualization widget won't load and I'm having a difficult time tracking down the source of the problem. When using the "mcorr_cnmy.ipynb" demo notebook I always get the following errors (see attached photo). Any ideas on what I can try to fix this?
![Capture](https://github.com/nel-lab/mesmerize-core/assets/62612214/27acddb4-98c4-4edf-8d2d-ce3f79a32704)
![Capture1](https://github.com/nel-lab/mesmerize-core/assets/62612214/bddd2540-3618-42bc-8709-0c1ee0d5e083)

**Comment by kushalkolar** [comment]
Did you install mesmerize-viz? The JavaScript errors show that jupyter_rfb and ipydatagrid aren't installed. They get installed when you install mesmerize-viz.

**Comment by blogeman** [comment]
The following output won't show the version of mesmerize-viz, but the attached picture from the output of conda list shows that it is version 0.1.0b1

In [8]: mesmerize_core.__version__
Out[8]: '0.3.0'

In [9]: mesmerize_viz.__version__
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[9], line 1
----> 1 mesmerize_viz.__version__

AttributeError: module 'mesmerize_viz' has no attribute '__version__'

![Capture](https://github.com/nel-lab/mesmerize-core/assets/62612214/df6c8cf4-e220-4d59-a7da-0eecd042d79b)

**Comment by blogeman** [comment]
Also it appears that jupyter-rfb is installed at version 0.4.2 and ipydatagrid is installed at version 1.2.1

**Comment by kushalkolar** [comment]
Do you launch jupyterlab from one env and then launch a kernel using Python
in another env? If so see this
https://github.com/vispy/jupyter_rfb/issues/86

**Comment by blogeman** [comment]
That is exactly what I have been doing, launching jupyterlab from a base environment and then switching to a kernel for a different conda environment. Installing jupyter-rfb and ipydatagrid in the base environment seems to have done the trick. Many thanks!

**Comment by kushalkolar** [comment]
My recommendation would be to launch jupyterlab directly from the env with mesmerize-core, mesmerize-viz, jupyter_rfb, and all other ipywidget libs. Otherwise you have to worry about versions matching between your base env and the other envs: https://github.com/Anaconda-Platform/nb_conda_kernels/issues/201#issuecomment-901068937
