### ISSUE TITLE
motion correction failed 

### ISSUE THREAD

**Issue by Frank497** [nel-lab/mesmerize-core#280]
I was trying out the mcorr_cnmf demo notebook and successfully ran the codes and set up dataframe. However, when I perform motion correction (in the "Run an item" section) it gives:
![螢幕擷取畫面 2024-03-04 112254](https://github.com/nel-lab/mesmerize-core/assets/73454537/de30b5a5-b19b-49fc-b626-f48d0e81354a)

and I ignored it and ran the rest of the code and got this in the "Output" section:
![螢幕擷取畫面 2024-03-04 112209](https://github.com/nel-lab/mesmerize-core/assets/73454537/b9f56af0-9554-4b2b-9170-f925be05b9fb)
I wonder what went wrong and how could I fix it.

**Comment by kushalkolar** [comment]
I have a hunch that the latest version of caiman changed imports which then broke thing in `movies.get_file_size()`. What version of caiman are you on and what version of mesmerize-core?

**Comment by kushalkolar** [comment]
posted an issue at caiman repo: https://github.com/flatironinstitute/CaImAn/issues/1295

**Comment by kushalkolar** [comment]
@Frank497 if you go down to v1.10.2 it should work

**Comment by Frank497** [comment]
@kushalkolar It do fixed the problem to downgrade the caiman version to v1.10.2. The motion correction performs successfully now, however I met [another problem on visualization now](https://github.com/kushalkolar/mesmerize-viz/issues/41)
