### ISSUE TITLE
ModuleNotFoundError: No module named 'mesmerize_viz'

### ISSUE THREAD

**Issue by zhouyi0812** [nel-lab/mesmerize-core#283]
Hello! 
I run cnmfe today and found there is an error show in title, I uninstall the viz and reinstall, but the error still there.
Thank you!

**Comment by kushalkolar** [comment]
You're probably in another env

**Comment by zhouyi0812** [comment]
Thank  you!!
And I also found another error when define the shape:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[18], line 1
----> 1 a = LazyTiff(df.iloc[0].caiman.get_input_movie_path())
      2 a.shape

File [~\anaconda3\envs\mescore\lib\site-packages\mesmerize_core\arrays\_tiff.py:27](http://localhost:8889/lab/tree/caiman_data/demos/notebooks/~/anaconda3/envs/mescore/lib/site-packages/mesmerize_core/arrays/_tiff.py#line=26), in LazyTiff.__init__(self, path, shape)
     13 """
     14 Lazy reader for tiff files. WIP, works for some tiff files.
     15 Try ``tifffile.memmap`` first before trying ``LazyTiff``
   (...)
     23     manually set shape
     24 """
     26 self._tif = tifffile.TiffFile(path)
---> 27 tiffseries = self._tif.series[0].levels[0]
     29 if shape is None:
     30     # TODO: someone who's better with tiff can help on this
     31     if len(self._tif.pages) == 1:

AttributeError: 'TiffPageSeries' object has no attribute 'levels'

This time I was successfully run the mesmerize-viz

Thank you!

**Comment by kushalkolar** [comment]
This is a different thing, please post a new issue.
