### ISSUE TITLE
Module 'fpl' has no attribute 'ImageWidget'

### ISSUE THREAD

**Issue by lea-danics** [nel-lab/mesmerize-core#290]
Hi Everyone!
I'm running into an attribure error when I'm trying to run this code from cnmfe.ipynb demo notebook:
# input movie will be shown on left, filtered on right
iw_gs = fpl.ImageWidget(
    data=[input_movie, input_movie.copy()],
    frame_apply=funcs,
    names=["raw", "filtered"],
    grid_plot_kwargs={"size": (1200, 600)},
    cmap="gnuplot2"
)

The error is the following:
AttributeError                            Traceback (most recent call last)
Cell In[3], line 2
      1 # input movie will be shown on left, filtered on right
----> 2 iw_gs = fpl.ImageWidget(
      3     data=[input_movie, input_movie.copy()],
      4     frame_apply=funcs,
      5     names=["raw", "filtered"],
      6     grid_plot_kwargs={"size": (1200, 600)},
      7     cmap="gnuplot2"
      8 )
AttributeError: module 'fpl' has no attribute 'ImageWidget'

I installed and imported fpl.

I tried to find similar issues, but I couldn't find solution to my problem.

**Comment by kushalkolar** [comment]
Did you install mesmerize-viz?

**Comment by lea-danics** [comment]
Yes, that solved the problem ,thank You very much!!!
