### ISSUE TITLE
No matching distribution found for LazyTiff

### ISSUE THREAD

**Issue by lea-danics** [nel-lab/mesmerize-core#292]
Dear Kushal,

I cannot overcome at the following point of cnmfe demo workbook:
a = LazyTiff(df.iloc[0].caiman.get_input_movie_path())
      2 a.shape
      
 NameError: name 'LazyTiff' is not defined
 
 I couldn't import neither install LazyTiff.
 
 When I tried to install I got ERROR: Could not find a version that satisfies the requirement lazytiff (from versions: none)
ERROR: No matching distribution found for lazytiff

For installation I tried this code in (mescore) PS C: C:\Users\danic
git clone https://github.com/plimkilde/lazytiff.git
cd lazytiff
pip install lazytiff

Thanks for the help in advance!!

**Comment by kushalkolar** [comment]
LazyTiff is a mescore loader but I'd really just recommend using tiffit by @EricThomson (check his repo) to convert your tiff files so that they're memmapable (I'm assuming you don't have memmapable tiff files right now), which makes them much nicer to deal with.

**Comment by lea-danics** [comment]
Thank You!
I installed tiffit as well. Than should I only modify the code?
e.g. a = tiffit(df.iloc[0].caiman.get_input_movie_path())
2 a.shape

Thanks for the help!

**Comment by EricThomson** [comment]
tiffit is a command line interface so at the command line  you can convert your movies to a "good" format before you start your analysisa, before you do anything in jupyter. So in your anaconda prompt (or whatever command line you run jupyter from), you activate your virtual environment, and then, if you have a "bad" tiff file named `bad.tiff`, create a good tiff file with:

`tiffit convert bad.tiff good.tiff`

Then you do your analysis on `good.tiff`

**Comment by kushalkolar** [comment]
> Thank You! I installed tiffit as well. Than should I only modify the code? e.g. a = tiffit(df.iloc[0].caiman.get_input_movie_path()) 2 a.shape
> 
> Thanks for the help!

Can you please tell us what you're trying to do, the full context.

**Comment by kushalkolar** [comment]
Hi, I'm guessing you solved this, if not feel free to re-open :)
