### ISSUE TITLE
Motion correction output F order only

### ISSUE THREAD

**Issue by zhouyi0812** [nel-lab/mesmerize-core#296]
Hello!

I looped a bunch of movie for motion correction and found that the output is 'F' order only.
But when I use Caiman, it is 'C' order mmap file is being used.

How should I deal with it? It is possible to get C order for output?
Thank you!

**Comment by kushalkolar** [comment]
Motion correction uses F-order because that's the fastest way to access frames, CNMF uses C-order because that's the fastest way to access individual pixels.
