### ISSUE TITLE
caiman extension get_spatial_masks()

### ISSUE THREAD

**Issue by clewis7** [nel-lab/mesmerize-core#30]
![Screenshot_20220529_204926](https://user-images.githubusercontent.com/69729525/170899060-c44fcc2c-9423-40a8-a916-ca4e4f7ca1b7.png)
![Screenshot_20220529_205021](https://user-images.githubusercontent.com/69729525/170899080-4998805a-ce99-4240-ac03-59ab97387228.png)

using caiman extension to ```get_spatial_masks()``` does not plot properly...not filling in neurons

**Comment by kushalkolar** [comment]
not happening
