### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by CharlotteWenxin** [nel-lab/mesmerize-core#301]
I'm using Windows 11 with AMD Ryzen 7 7800X3D 8-Core Processor, 4201 Mhz, 8 Core(s), 16 Logical Processor(s).

I have installed caiman first and it works. Then I installed mesmerize-core in the caiman environment but I cannot activate it with 'mamba activate mescore'. So I deleted the caiman environment and tried: mamba create -n mescore -c conda-forge mesmerize-core. Then I have this error: The following package could not be installed
└─ mesmerize-core is not installable because it requires
   └─ caiman >=1.9.10 , which requires
      └─ tensorflow [>=2.4.0 |>=2.4.0,<2.16 ], which conflicts with any installable versions previously reported.

![image](https://github.com/nel-lab/mesmerize-core/assets/157476627/b6dc9a98-a5b6-4e14-a05d-0eb1d29914fc)

I'm pretty new to this. Thank you very much for the help in advance!

**Comment by CharlotteWenxin** [comment]
I found the solution: conda config --set channel_priority flexible

**Comment by kushalkolar** [comment]
@pgunn is this a new thing where they have to set channel priority as flexible?

**Comment by pgunn** [comment]
@kushalkolar If they're on Windows and they're using a conda distro where it's not flexible by default, yes.
