### ISSUE TITLE
lru_cache doesn't work with 'np.ndarray' as argument

### ISSUE THREAD

**Issue by ArjunPutcha** [nel-lab/mesmerize-core#31]
See cnmf.py, CNMFExtensions._get_spatial_contours
Passing np.ndarray for ixs_components yields the following error: "TypeError: unhashable type: 'numpy.ndarray'"

**Comment by kushalkolar** [comment]
@clewis7 it would be useful to add tests to check the return vals of these functions with `ixs_components` passed, as well as different combinations of kwargs when relevant.

**Comment by kushalkolar** [comment]
custom LRU cache being implemented in #62
