### ISSUE TITLE
Current status of mesmerize-viz and fastplotlib?

### ISSUE THREAD

**Issue by FlynnOConnell** [nel-lab/mesmerize-core#318]
Hi! I love mesmerize-core, and am looking to incorporate some mcorr/cnmf visualizations but I'm not sure the best way to proceed. Mesmerize-viz pinned an old version of fastplotlib that no longer works due to API changes to Plot() and Figure(). I can't get those visualizations to work, they only show the histogram on the side. I haven't been able to get mesmerize-viz or fastplotlib to work visualizing the results.

I'm wondering if you'd recommend using mesmerize-viz, or fixing the issues I'm having with fastplotlib (all kinds of wgpu canvas errors). In either case I can move to the corresponding repository with my issue. 

I am really encouraged by this widget added below, produced with mesmerize-viz. But I can't produce this graphic reliably, and it doesn't work with motion correction. Further, I can't use other fastplotlib examples due to the API changes.

![image](https://github.com/user-attachments/assets/2491f7d1-89a0-4deb-8000-cdd4c6533528)

I would be happy to make contributions, I'm primarily asking where these contributions should be focused. 

Thank!

**Comment by kushalkolar** [comment]
Hi, thanks for posting and we're happy that you find it useful!

While this project is being actively maintained, we currently do not have the time to bring it up to date with the latest fastplotlib. Contributions are welcome and I'd be happy to review a PR to update mesmerize-viz to work with the next release of fastplotlib (current fastplotlib@main). Fastplotlib is a larger separate project. 

Your other questions:

> they only show the histogram on the side.

I'm confused, in the image you show that it does work? Is this between machines? I've seen this before when it's a driver issue, see: https://github.com/kushalkolar/mesmerize-viz/issues/41

> But I can't produce this graphic reliably, and it doesn't work with motion correction.

What exactly do you get, does the python kernel die? What's your hardware and what OS, how much VRAM?

It looks like you have a lot of contours, drawing nice line is very computationally intensive on the gpu. I plan to do this at some point to get around it for these types of use cases: https://github.com/fastplotlib/fastplotlib/issues/258

It you want to take a shot at it I'm happy to review a PR! 

> Further, I can't use other fastplotlib examples due to the API changes.

If you're referring to the fastplotlib example gallery then that requires the latest release or main :) 

BTW if you're at Rockefeller, we're only a few blocks away if you want to visit!

**Comment by FlynnOConnell** [comment]
Hi Kushal, 

Sorry for the delay! The image shown above is a mostly working version of the cnmf mesmerize-viz visualization. **A clean miniconda installation fixed the heatmap not rendering**. I think I need to become a bit more familiar with the current fastplotlib API, as I haven't used it much but I really see its value. Since the mesmerize-viz widgets are working properly, I 

Rendering manymany contours is definitely an area we will have to tackle. This may be a good topic to chat about in person. :) 

I will contact via email and put any further issues in the corresponding project the issue pertains to.
