### ISSUE TITLE
Delete associated files when removing batch item

### ISSUE THREAD

**Issue by ArjunPutcha** [nel-lab/mesmerize-core#40]
When removing a batch item, there should be an option (or default with option for not doing) to delete all files with the same uuid

**Comment by kushalkolar** [comment]
Deletion should be safe. If output of item X (for example mcorr) is input to item Y, then use a kwarg "safe_removal" to determine if X should be deleted.

**Comment by kushalkolar** [comment]
Add DataFrame extension to check dependencies. For example, X.children will return the UUIDs of all items where X.uuid is found in Y.input_movie_path

Similarly have Y.parents which returns UUIDs of all items where Y.uuid is prevent in X.outputs.values
