### ISSUE TITLE
Installation error - "cannot import name 'init_std_stream_encoding' from 'conda.common.compat' "

### ISSUE THREAD

**Issue by GarrettBlair** [nel-lab/mesmerize-core#49]
OS - Windows 11

Hey guys, while installing mesmerize-core for development I got an error while updating the env with the environment file:

(mesmerize-core) C:\Users\gjb326\mesmerize-core>`mamba env update -n mesmerize-core --file environment.yml`
Traceback (most recent call last):
--File "C:\Users\gjb326\Anaconda3\Scripts\mamba-script.py", line 10, in <module>
----sys.exit(main())
--File "C:\Users\gjb326\Anaconda3\lib\site-packages\mamba\mamba.py", line 848, in main
----from conda.common.compat import ensure_text_type, init_std_stream_encoding
ImportError: cannot import name 'init_std_stream_encoding' from 'conda.common.compat' (C:\Users\gjb326\Anaconda3\lib\site-packages\conda\common\compat.py)

**Comment by kushalkolar** [comment]
seems like it has to do with `conda` and `mamba` versions conflicting https://github.com/mamba-org/mamba/issues/1706

**Comment by GarrettBlair** [comment]
Just tried installing again. I think `jupyterlab` was somehow messing up my environment pah variables, after fixing them, removing `jupyterlab`, and reinstalling `mamba` I didn't encounter this error again. I'm not sure why that seems to have fixed it, But I'd guess it was because my environment variables path was messed up.

**Comment by kushalkolar** [comment]
Thanks for sharing! If you've solved it you can close the issue.
