### ISSUE TITLE
Installation - problem while solving environment

### ISSUE THREAD

**Issue by GarrettBlair** [nel-lab/mesmerize-core#53]
While trying to update the environment via mamba:
`mamba env update -n mesmerize-core --file environment.yml`
ERROR: 
Encountered problems while solving:
  - package caiman-1.9.10-py39h2e25243_0 requires python >=3.9,<3.10.0a0, but none of the providers can be installed

checking the installed `python --version` = 3.10.4
Then I tried `conda install python=3.10.0`, rerunning the env update yielded the same error

Next `conda install python=3.9` made the env update work. 

Should I just continue with 3.9, or use something else?

**Comment by kushalkolar** [comment]
What OS? The CI pipeline with Python 3.10 and conda works on Ubuntu, but the Python venv CI pipeline is on 3.9 so you should be fine.

Just note that you'll need to install pandas straight from GitHub until they release v1.5.0

**Comment by GarrettBlair** [comment]
Windows 11 OS

I did get the pandas installed just fine

**Comment by kushalkolar** [comment]
If the tests pass on your end you're good to go!

**Comment by GarrettBlair** [comment]
I'm getting directory errors when running the tests, unsure if it's related or how to fix it:

`pytest -s .`
=== test session starts ===
platform win32 -- Python 3.9.12, pytest-7.1.2, pluggy-1.0.0
rootdir: C:\Users\gjb326\mesmerize-core

collected 5 items
full errors - https://pastebin.com/nN2pTY22

5 fails, 158 warnings

FAILED tests/test_core.py::test_create_batch - ValueError: Paths must only contain alphanumeric characters, hyphens ( - ), underscores ( _ ) or periods ( . )
FAILED tests/test_core.py::test_mcorr - ValueError: Paths must only contain alphanumeric characters, hyphens ( - ), underscores ( _ ) or periods ( . )
FAILED tests/test_core.py::test_cnmf - ValueError: Paths must only contain alphanumeric characters, hyphens ( - ), underscores ( _ ) or periods ( . )
FAILED tests/test_core.py::test_cnmfe - ValueError: Paths must only contain alphanumeric characters, hyphens ( - ), underscores ( _ ) or periods ( . )
FAILED tests/test_core.py::test_remove_item - ValueError: Paths must only contain alphanumeric characters, hyphens ( - ), underscores ( _ ) or periods ( . )

The paths look alright to me
path = 'C:\\Users\\gjb326\\mesmerize-core\\tests\\tmp\\c6de2a65-c03e-4076-83dd-ef464d5a324e.pickle'
path = WindowsPath('C:/Users/gjb326/mesmerize-core/tests/videos')

**Comment by kushalkolar** [comment]
Thanks for trying this out on Windows! Looks like I needed an extra `\` character in the regex validator for paths, fixed in https://github.com/nel-lab/mesmerize-core/commit/45ce26d127e4259f182737c76801a227dd0c61b6 in `master`, should work now.
