### ISSUE TITLE
move `CaimanSeriesExtensions._run_qprocess` to mesmerize-napari

### ISSUE THREAD

**Issue by kushalkolar** [nel-lab/mesmerize-core#72]
It should be possible to subclass `CaimanSeriesExtensions` in `mesmerize-napari` and append the `_run_qprocess()` method to that, this way `mesmerize-core` gets rid of Qt completely!

@ArjunPutcha

**Comment by ArjunPutcha** [comment]
I believe this is done. Shall we close this issue?

**Comment by kushalkolar** [comment]
tested and works in napari?

**Comment by kushalkolar** [comment]
I'm closing this here.
